# 🏠 Property Finder Egypt Scraper
### Sale & Rent Listings

### Made By: Eng. Elsayed Bakry
This notebook scrapes property listings from **Property Finder Egypt** (`propertyfinder.eg`).

**How to use:**
1. Run **Cell 1** once to install dependencies.
2. Run **Cell 2** to import libraries.
3. Run **Cell 3** to define the shared `get_driver()` helper.
4. Run **Cell 4 / 5** for Sale / Rent listings — each is fully independent.
5. Run **Cell 6** to merge all scraped data into one CSV.

> ⚙️ **Settings** — change `MAX_PAGES` (default **50**) and `OUTPUT_FILE` at the top of each scraper cell.
> 🔇 To run without opening a browser window, uncomment the `--headless=new` line inside `get_driver()`.

## Cell 1 — Install dependencies
Run this **once**. Skip on subsequent runs if packages are already installed.

In [1]:
!pip install -q selenium pandas webdriver-manager pytz

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: C:\Users\5g\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Cell 2 — Imports
Standard libraries used by every scraper below.

In [2]:
import re
import time
import pandas as pd
from datetime import datetime, timedelta
import pytz

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

print("✅ Imports ready")

✅ Imports ready

## Cell 3 — Shared helper
One reusable function used by every scraper:

- **`get_driver()`** — launches a Chrome browser with anti-bot settings.

In [3]:
# ─────────────────────────────────────────────────────────────────
# get_driver() — returns a configured Chrome WebDriver instance
# ─────────────────────────────────────────────────────────────────

def get_driver():
    """Launch Chrome with settings that reduce bot-detection."""
    options = Options()

    # Uncomment the next line to run without opening a browser window:
    # options.add_argument("--headless=new")

    options.add_argument("--start-maximized")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option("useAutomationExtension", False)

    driver = webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=options
    )
    # Mask navigator.webdriver flag
    driver.execute_cdp_cmd(
        "Page.addScriptToEvaluateOnNewDocument",
        {"source": "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"}
    )
    return driver


print("✅ Helper functions defined")

✅ Helper functions defined

## Cell 4a — Scrape Agencies
Scrapes **41 pages** of agencies from `propertyfinder.eg/ar/find-broker/search`.
Stores agency **logo URL** and **name** in `agencies_df`.
This DataFrame is later used to match agency logos from property listings to real names.

In [11]:
# ── Settings ──────────────────────────────────────────────────────
AGENCY_BASE_URL  = "https://www.propertyfinder.eg/ar/find-broker/search"
AGENCY_MAX_PAGES = 41
# ──────────────────────────────────────────────────────────────────


def normalize_logo_url(url):
    """Remove resolution segment (e.g. /260x200, /178x98) from logo URLs
    so the same logo at different sizes maps to the same lookup key."""
    if not url:
        return None
    import re
    return re.sub(r'/\d+x\d+(\.\w+)$', r'\1', url)


def get_logo_url(driver, img_el):
    """Extract real logo URL, handling lazy-loaded placeholder gifs."""
    PLACEHOLDER = ("data:image", "data:application")

    def is_real(u):
        return bool(u) and not any(u.startswith(p) for p in PLACEHOLDER)

    # 1. src
    src = img_el.get_attribute("src") or ""
    if is_real(src):
        return src

    # 2. data-src
    data_src = img_el.get_attribute("data-src") or ""
    if is_real(data_src):
        return data_src

    # 3. srcset — take first URL
    srcset = img_el.get_attribute("srcset") or ""
    if srcset:
        first = srcset.split(",")[0].strip().split(" ")[0]
        if is_real(first):
            return first

    # 4. Scroll into view and retry once
    driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", img_el)
    time.sleep(0.4)
    src = img_el.get_attribute("src") or ""
    if is_real(src):
        return src

    return None


def scrape_agencies(base_url=AGENCY_BASE_URL, max_pages=AGENCY_MAX_PAGES):
    driver       = get_driver()
    all_agencies = []
    seen_names   = set()

    for page in range(1, max_pages + 1):
        page_url = f"{base_url}?page={page}"
        print(f"\n{'='*40}")
        print(f"  AGENCIES PAGE {page}  →  {page_url}")
        print(f"{'='*40}")

        driver.get(page_url)

        try:
            WebDriverWait(driver, 20).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, 'li[data-testid="list-card"]'))
            )
        except Exception:
            print("⚠️  Timed-out waiting for agency cards — stopping.")
            break

        # Scroll slowly down the page to trigger lazy-loading for all images
        page_height = driver.execute_script("return document.body.scrollHeight")
        for y in range(0, page_height, 400):
            driver.execute_script(f"window.scrollTo(0, {y});")
            time.sleep(0.08)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(1.5)

        cards = driver.find_elements(By.CSS_SELECTOR, 'li[data-testid="list-card"]')
        print(f"Found {len(cards)} agency cards")

        if not cards:
            print("⚠️  No cards found — stopping.")
            break

        for card in cards:
            try:
                try:
                    name = card.find_element(By.TAG_NAME, "h2").text.strip()
                except Exception:
                    name = None

                try:
                    img_el   = card.find_element(By.CSS_SELECTOR, 'img[data-testid="card-image"]')
                    raw_logo = get_logo_url(driver, img_el)
                    logo_url = normalize_logo_url(raw_logo)
                except Exception:
                    logo_url = None

                dedup_key = name or logo_url
                if dedup_key and dedup_key in seen_names:
                    continue
                if dedup_key:
                    seen_names.add(dedup_key)

                all_agencies.append({"agency_name": name, "agency_logo": logo_url})
                print(f"  + {name}  {'✅' if logo_url else '⚠️  no logo'}")

            except Exception as e:
                print(f"  ⚠️  Agency card error: {e}")

    driver.quit()

    agencies_df = pd.DataFrame(all_agencies)
    real_logos  = agencies_df["agency_logo"].notna().sum()
    print(f"\n✅ Agencies scraping done — {len(agencies_df)} agencies ({real_logos} with logo)")
    return agencies_df


# ── Run ───────────────────────────────────────────────────────────
agencies_df = scrape_agencies()
agencies_df.head(10)

========================================
  AGENCIES PAGE 1  →  https://www.propertyfinder.eg/ar/find-broker/search?page=1
========================================
Found 20 agency cards
  + Coldwell Banker Wealth  ✅
  + Selection Code  ✅
  + Square real estate  ✅
  + New Avenue Real Estate  ✅
  + Master Mind Real Estate Services  ✅
  + Spade consultancy  ✅
  + Egypt Best Properties  ✅
  + IRTKAZ  ✅
  + Select for real estate  ✅
  + Property Hills Star  ✅
  + Remax Professional.  ✅
  + Summit Real Estate  ✅
  + Insider Real Estate Consultancy  ✅
  + Property Hills.  ✅
  + Closer  ✅
  + Falcon for Real Estate  ✅
  + Platinum Properties  ✅
  + Allocate Real Estate  ✅
  + CBE New Homes  ✅
  + Go Green Egypt Real Estate  ✅

========================================
  AGENCIES PAGE 2  →  https://www.propertyfinder.eg/ar/find-broker/search?page=2
========================================
Found 20 agency cards
  + Abrag 2  ✅
  + Abrag Real Estate  ✅
  + Adviser Real Estate  ✅
  + Edge Real Estates  ✅
  + Citizen Home  ✅
  + AK Circle  ✅
  + Premier Property  ✅
  + Property Hills VIP  ✅
  + why solutions  ✅
  + Home Realtors  ✅
  + Next Door Consultancy  ✅
  + EDGE  ✅
  + Premium Real estate  ✅
  + Evergreen Properties  ✅
  + Sonic For Real-Estate  ✅
  + GCR Developments  ✅
  + Mrkt Shake  ✅
  + SQUARE9  ✅
  + Roots Real Estate  ✅
  + Roots Development  ✅

========================================
  AGENCIES PAGE 3  →  https://www.propertyfinder.eg/ar/find-broker/search?page=3
========================================
Found 20 agency cards
  + One Estates Real Estate  ✅
  + Experts Home  ✅
  + Tradmark Real Estate  ✅
  + EMERALD REAL ESTATE  ✅
  + Regypt  ✅
  + Al Maz Real Estate  ✅
  + Brand Facility Management  ✅
  + Do estate  ✅
  + Brokerage Hub  ✅
  + New Capital Home.  ✅
  + Aqarpedia For Resale  ✅
  + Property Network  ✅
  + Treasure Real estate  ✅
  + Hurghadians Property  ✅
  + Apart Real estate  ✅
  + I-Move  ✅
  + Crown Stone Realty  ✅
  + Golden Key  ✅
  + Rokn Real Estate  ✅
  + ERE Investments  ✅

========================================
  AGENCIES PAGE 4  →  https://www.propertyfinder.eg/ar/find-broker/search?page=4
========================================
Found 20 agency cards
  + Trends Real Estate Egypt  ✅
  + Onyx for real estate  ✅
  + Mr .Estates  ✅
  + Akar Town Real Estate  ✅
  + Impact Investments  ✅
  + Step One Real Estate  ✅
  + Coldwell Banker Platinum  ✅
  + property hills Elite  ✅
  + Views for Real Estate  ✅
  + Conquer Properties  ✅
  + Assets Real Estate Investments  ✅
  + Gate real estate marketing  ✅
  + Homes Bay  ✅
  + COB  ✅
  + Century for Project Management  ✅
  + Property Hills...  ✅
  + Realm Properties  ✅
  + New Destination Real Estate Consultancy  ✅
  + Elshams Real Estate  ✅
  + Ninety Two  ✅

========================================
  AGENCIES PAGE 5  →  https://www.propertyfinder.eg/ar/find-broker/search?page=5
========================================
Found 20 agency cards
  + Oaks Real Estate  ✅
  + Coldwell Banker- The Blues  ✅
  + Capital Lords Real Estate  ✅
  + AQARY For Real Estate  ✅
  + BGCO Real Estate  ✅
  + I-Zone  ✅
  + Homescout  ✅
  + Properties-Today.com  ✅
  + Driven Properties  ✅
  + Guides Real Estate  ✅
  + رابح للتسويق العقاري  ✅
  + ARC Investments  ✅
  + ERE  ✅
  + Hodoud for Real Estate  ✅
  + Citygate Resale  ✅
  + The Way  ✅
  + Kayan Real Estate & Property Management  ✅
  + Held Real Estate  ✅
  + Global Marketing Real Estate  ✅
  + RE/MAX Everest  ✅

========================================
  AGENCIES PAGE 6  →  https://www.propertyfinder.eg/ar/find-broker/search?page=6
========================================
Found 20 agency cards
  + Promax Property Investors  ✅
  + Dwell elite  ✅
  + Osoul Misr  ✅
  + RE/MAX Al Mohager  ✅
  + Home Select for real estate  ✅
  + Commercial State  ✅
  + YaKan Properties  ✅
  + Al Ahly Sabbour  ✅
  + Horizon Estate  ✅
  + Inn Properties  ✅
  + Bright  ✅
  + Property Hills One  ✅
  + CLICK  ✅
  + The 8 For Real Estate Solutions  ✅
  + Houseology  ✅
  + Vida Solutions  ✅
  + Bold Egypt  ✅
  + Dream Homes Real Estate  ✅
  + Darak Madinaty  ✅
  + Inspire Homes  ✅

========================================
  AGENCIES PAGE 7  →  https://www.propertyfinder.eg/ar/find-broker/search?page=7
========================================
Found 20 agency cards
  + Experts Real Estate Investment  ✅
  + RE/MAX Avalon  ✅
  + Your Real Estate  ✅
  + شقتي للتسويق العقاري و ادارة المشروعات  ✅
  + Regus-Egypt  ✅
  + Home Valley  ✅
  + Gaby's Homes  ✅
  + Path Finder  ✅
  + Three in one Investment  ✅
  + Haven Estate  ✅
  + Golden Gates Real Estate  ✅
  + Places Solution  ✅
  + THE SECRET INVESTMENT  ✅
  + iHome  ✅
  + North Edge  ✅
  + Revox  ✅
  + Tasweeq For Real Estate  ✅
  + SKEEP  ✅
  + Fortune Real Estate  ✅
  + Western House  ✅

========================================
  AGENCIES PAGE 8  →  https://www.propertyfinder.eg/ar/find-broker/search?page=8
========================================
Found 20 agency cards
  + INST8 Real Estate Consultancy  ✅
  + MH For Real Estate  ✅
  + Engaz Real Estate  ✅
  + Emtdad Real Estate  ✅
  + ETHOS  ✅
  + Zayed Homes  ✅
  + Home Agent  ✅
  + Scale for Real estate investments  ✅
  + Premium Homes  ✅
  + Bigger Asset  ✅
  + -رواسي للاستثمار العقاري-  ✅
  + El Hefny Group  ✅
  + Clustra Real Estate Consultancy  ✅
  + Santorini  ✅
  + New Edge  ✅
  + Momentum  ✅
  + Right Direction  ✅
  + Sky Hills For Real Estate  ✅
  + El Hady Real Estate Investment  ✅
  + بروبيرتي هيلز ون  ✅

========================================
  AGENCIES PAGE 9  →  https://www.propertyfinder.eg/ar/find-broker/search?page=9
========================================
Found 20 agency cards
  + New Casa Real estate  ✅
  + TDA Real Estate  ✅
  + Anchor for Real Estate  ✅
  + GNY Real Estate  ✅
  + MD Signature 1  ✅
  + El-Moustafa For Real Estate  ✅
  + Prime Homes  ✅
  + Bitak  ✅
  + Hidden Homes  ✅
  + The Realestate experts  ✅
  + La Quinta  ✅
  + Property Guide.  ✅
  + Skyline  ✅
  + Four Bond  ✅
  + Smart Location Group  ✅
  + D.Signature  ✅
  + REV Real Estate  ✅
  + Wdeals for real estate  ✅
  + Elegant Home  ✅
  + Redefine  ✅

========================================
  AGENCIES PAGE 10  →  https://www.propertyfinder.eg/ar/find-broker/search?page=10
========================================
Found 20 agency cards
  + DMG  ✅
  + Ammaier for real estate  ✅
  + Wealthiest Real Estate management  ✅
  + Home Way  ✅
  + Magic Real Estate  ✅
  + Property Group  ✅
  + Estimate Investment  ✅
  + Hyde Park Developments  ✅
  + Prime Company  ✅
  + Homes Egypt  ✅
  + Residia  ✅
  + Maskan Consultancy  ✅
  + MD Signature  ✅
  + Cairo Gate  ✅
  + Aka Group Real estate  ✅
  + Triple S Real Estate  ✅
  + Wonder Homes For Real Estate  ✅
  + Selective  ✅
  + Square Properties  ✅
  + Makanak Investments  ✅

========================================
  AGENCIES PAGE 11  →  https://www.propertyfinder.eg/ar/find-broker/search?page=11
========================================
Found 20 agency cards
  + Key Point for real estate  ✅
  + Aqar Misr  ✅
  + Buyerside  ✅
  + Q Sequoie  ✅
  + Oqood Investments  ✅
  + Najd Real Estate  ✅
  + Country For Real Estate  ✅
  + TREX  ✅
  + Crown properties  ✅
  + ERA Real Estate Egypt  ✅
  + Image Investments  ✅
  + Corporate Deals  ✅
  + Smart Step  ✅
  + Full House West  ✅
  + Boundless For Real Estate  ✅
  + Flag square Real Estate  ✅
  + Al Fanar Development and project management  ✅
  + Premises  ✅
  + The Polygon  ✅
  + Realtors  ✅

========================================
  AGENCIES PAGE 12  →  https://www.propertyfinder.eg/ar/find-broker/search?page=12
========================================
Found 20 agency cards
  + Towers Map  ✅
  + Element Estate  ✅
  + Rank For Real Estate  ✅
  + I properties Real Estate Consultant  ✅
  + The Choice For Real Estate  ✅
  + plan-B  ✅
  + Circle Realestate  ✅
  + VERKKINS  ✅
  + Infinity Homes  ✅
  + Modern Homes realestate  ✅
  + Nile House For Real Estate  ✅
  + New Arkan Properties  ✅
  + SG Real Estate  ✅
  + Capital Property  ✅
  + AMG.  ✅
  + El Kateb Real Estate  ✅
  + Vertex Estate  ✅
  + Aspire Properties  ✅
  + The Broker EG  ✅
  + ZF Property  ✅

========================================
  AGENCIES PAGE 13  →  https://www.propertyfinder.eg/ar/find-broker/search?page=13
========================================
Found 20 agency cards
  + Element  ✅
  + Value For Real Estate  ✅
  + Smart Home  ✅
  + In2Rent  ✅
  + Gold Routes  ✅
  + Triple V Real Estate Consultancy  ✅
  + Rikaz  ✅
  + Contract Madinaty  ✅
  + Homy Real Estate  ✅
  + Top Homes Real Estate  ✅
  + Commercial Square  ✅
  + S signature  ✅
  + Sedra Real Estate  ✅
  + sms for RealEstate  ✅
  + ABAZA for real estate  ✅
  + Real Vision  ✅
  + Picky Properties  ✅
  + Sign Real Estate  ✅
  + Global holdings  ✅
  + The Light For Real Estate  ✅

========================================
  AGENCIES PAGE 14  →  https://www.propertyfinder.eg/ar/find-broker/search?page=14
========================================
Found 20 agency cards
  + Code For Real Estate  ✅
  + العصامي للتسويق و الاستثمار العقاري  ✅
  + Galaxy Real Estate  ✅
  + Iskan West  ✅
  + EstateLink  ✅
  + Emkan for Real Estate  ✅
  + Brokers Hub  ✅
  + Al Mada'in  ✅
  + Naeem Developments  ✅
  + bnb  ✅
  + Waystar Investment  ✅
  + Topaz Real Estate  ✅
  + Good Vibe Homes  ✅
  + Morshedy Group - Land Mark  ✅
  + NABAJ  ✅
  + Arsam Real-estate  ✅
  + Morshedy Group  ✅
  + Green Homes Real estate Agency  ✅
  + Realpals Real Estate  ✅
  + Alarabia for Real Estate Investments  ✅

========================================
  AGENCIES PAGE 15  →  https://www.propertyfinder.eg/ar/find-broker/search?page=15
========================================
Found 20 agency cards
  + CRV Real Estate Services  ✅
  + East wing  ✅
  + Elviro  ✅
  + We Comm  ✅
  + Darcom for Real Estate  ✅
  + Remax Jareed  ✅
  + Aqar Dayem  ✅
  + Home Destination  ✅
  + Another Way  ✅
  + بيتي للمقاولات  ✅
  + MRG Real Estate  ✅
  + Dwelling For Real Estate and Management  ✅
  + Massar  ✅
  + KAMF  ✅
  + Arabia For Real estate  ✅
  + Retaj Real Estate Consultancy  ✅
  + Horizen For Real Estate  ✅
  + ROCK VINE  ✅
  + Zein for real estate  ✅
  + Homevise Real Estate  ✅

========================================
  AGENCIES PAGE 16  →  https://www.propertyfinder.eg/ar/find-broker/search?page=16
========================================
Found 20 agency cards
  + Master Key  ✅
  + Smartex  ✅
  + Start Homes Madinaty  ✅
  + Core Real Estate Development  ✅
  + Brick Real Estate  ✅
  + Property insider  ✅
  + Smart Assets Real Estate  ✅
  + Contract Real Estate  ✅
  + views investment  ✅
  + BETA EGYPT  ✅
  + Crafters Real Estate  ✅
  + Tatari Investments  ✅
  + Amlak akareya  ✅
  + El-Nemr LTD  ✅
  + clear scope  ✅
  + Gold Real Estate  ✅
  + Arab City Group ( ACG )  ✅
  + LevelA  ✅
  + La Plage Group  ✅
  + Laucienda For Real Estate  ✅

========================================
  AGENCIES PAGE 17  →  https://www.propertyfinder.eg/ar/find-broker/search?page=17
========================================
Found 20 agency cards
  + Teleo For Real Estate  ✅
  + 929 Real Estate  ✅
  + I-Property  ✅
  + Scout Real Estate  ✅
  + Remax Bytek  ✅
  + Hirondelle Properties  ✅
  + Blu Real Estate Marketing  ✅
  + Vira Real Estate  ✅
  + JMG  ✅
  + La Costa For Real Estate  ✅
  + Wealth Platinum  ✅
  + Crown Developments  ✅
  + Hashtag Real estate  ✅
  + Hefnawy Group  ✅
  + ERMA Real Estate  ✅
  + Classy Home For Real Estate  ✅
  + Location Properties  ✅
  + Feeds  ✅
  + Dorra Developments  ✅
  + West Field  ✅

========================================
  AGENCIES PAGE 18  →  https://www.propertyfinder.eg/ar/find-broker/search?page=18
========================================
Found 20 agency cards
  + نوفاتيرا للتسويق العقاري  ✅
  + Chances Real Estate  ✅
  + BEYOTCOM  ✅
  + El-Bedihy & Co  ✅
  + Good Deals  ✅
  + Seals Consulting  ✅
  + EST8 | Real Estate Advisory  ✅
  + Better Estate Investment  ✅
  + Marina Home  ✅
  + ROI For Real Estate  ✅
  + 19 Rehab For RealEstate  ✅
  + ICONIC  ✅
  + E-Spaces  ✅
  + Dk REAL ESTATE  ✅
  + Flip  ✅
  + Find Estates  ✅
  + RE/MAX 1st Choice  ✅
  + KRE investments  ✅
  + Eureka Real Estate  ✅
  + MoveIn Egypt  ✅

========================================
  AGENCIES PAGE 19  →  https://www.propertyfinder.eg/ar/find-broker/search?page=19
========================================
Found 20 agency cards
  + Valero developments  ✅
  + City Properties  ✅
  + ElGammal real estate  ✅
  + Remax Top Agents  ✅
  + Blue Pearl  ✅
  + Eden Real Estate  ✅
  + Kayan El Aqaria  ✅
  + Chance for Realestate  ✅
  + البيت الابيض للاستثمار العقاري  ✅
  + Masar Real Estate  ✅
  + Homes Real Estate  ✅
  + Signature Broker  ✅
  + Makka Real Estate  ✅
  + Houses and More For Real Estate  ✅
  + Lennar For Real Estate  ✅
  + Shift Real Estate Solutions  ✅
  + Contact Madinaty Real Estate  ✅
  + الاولي العقارية  ✅
  + EnGaZ Real Estate  ✅
  + Property Misr  ✅

========================================
  AGENCIES PAGE 20  →  https://www.propertyfinder.eg/ar/find-broker/search?page=20
========================================
Found 20 agency cards
  + Grand House Real Estate  ✅
  + My Home  ✅
  + Ideal Real Estate  ✅
  + Amwaj  ✅
  + GREEN HOUSE  ✅
  + La Plaza Real Estate  ✅
  + INVEST PRO  ✅
  + GoldMark RealEstate  ✅
  + New Asset Investment  ✅
  + FIND HOUSE REALEstate  ✅
  + Sala Real-estate  ✅
  + Top Level  ✅
  + Ghoneim Real Estate  ✅
  + Nova Residence  ✅
  + Show Views  ✅
  + Auris For Project Management  ✅
  + Revalo Real Estate  ✅
  + Sky Line  ✅
  + الدوليه للتجارة والتسويق العقاري  ✅
  + Hello Home  ✅

========================================
  AGENCIES PAGE 21  →  https://www.propertyfinder.eg/ar/find-broker/search?page=21
========================================
Found 20 agency cards
  + Real Estate Agency  ✅
  + للتسويق العقاري S&f theSmart future  ✅
  + TA Real Estate  ✅
  + Horizon Homes  ✅
  + ستايل هوم  ✅
  + Premier Group  ✅
  + Manazil Egypt  ✅
  + Golden house  ✅
  + House Rock  ✅
  + Smart Move  ✅
  + Re/Max IBuild  ✅
  + Green House Real Estate  ✅
  + Sky Home  ✅
  + شركة التوحيد للعقارات  ✅
  + Projects Real Estate  ✅
  + Ahmed Hassan For Real Estate  ✅
  + Al Khabir Realestate  ✅
  + المصري للعقارات  ✅
  + Hussien Farahat  ✅
  + Art colorr  ✅

========================================
  AGENCIES PAGE 22  →  https://www.propertyfinder.eg/ar/find-broker/search?page=22
========================================
Found 20 agency cards
  + Dream Home  ✅
  + We are consultancy  ✅
  + بداية للاستثمار العقاري  ✅
  + ابتكار للتسويق العقاري  ✅
  + Trust  ✅
  + Rook Estate  ✅
  + Dm Consultation  ✅
  + Find Real Estate  ✅
  + Hurghada View Real Estate  ✅
  + The X Site For Real Estate  ✅
  + Lutazn For Real Estate  ✅
  + Pharos Real Estate  ✅
  + Line development  ✅
  + Knight properties  ✅
  + View For Real Estate  ✅
  + X Hub  ✅
  + Brokers East  ✅
  + Housey  ✅
  + Point Mark For Real Estate  ✅
  + Premium housing  ✅

========================================
  AGENCIES PAGE 23  →  https://www.propertyfinder.eg/ar/find-broker/search?page=23
========================================
Found 20 agency cards
  + My House (M&H)  ✅
  + The Homies  ✅
  + Muabark Group  ✅
  + Empire real estate and investment  ✅
  + Zone Abaza For Real Estate  ✅
  + Turnkey Solutions  ✅
  + Honesty Gate Real Estate  ✅
  + Baytak.  ✅
  + Future Square  ✅
  + Capital Commercial CCIM  ✅
  + Maadi Estate Agents  ✅
  + العقارية جروب  ✅
  + Mohamed Gaber  ✅
  + Future Home RealEstate  ✅
  + Dastan Real Estate  ✅
  + Alex Realestate  ✅
  + Byout Misr Property Consultancy  ✅
  + AL SAWAH GROUP  ✅
  + Adagio Real Estate  ✅
  + Concrete Real Estate  ✅

========================================
  AGENCIES PAGE 24  →  https://www.propertyfinder.eg/ar/find-broker/search?page=24
========================================
Found 20 agency cards
  + Mozdan For Real Estate  ✅
  + اصل المعمار  ✅
  + Rakar Investments  ✅
  + Real estate مكه  ✅
  + West City  ✅
  + Origin Real Estate  ✅
  + مكتب فيوتشر للعقارات  ✅
  + House Plus Real Estate  ✅
  + iFound Property  ✅
  + 4C Real Estate  ✅
  + Commission Real Estate  ✅
  + Compound Hekaya  ✅
  + Red House Real Estate  ✅
  + شركة البحيري جروب  ✅
  + Town Home Real Estate  ✅
  + Target Group  ✅
  + HA Group Rehab  ✅
  + Eastmark  ✅
  + Utopia  ✅
  + Eviča  ✅

========================================
  AGENCIES PAGE 25  →  https://www.propertyfinder.eg/ar/find-broker/search?page=25
========================================
Found 20 agency cards
  + Royal Home  ✅
  + AKARKOM R  ✅
  + galaxy house real estate  ✅
  + Green City for real estate  ✅
  + Time House  ✅
  + Jedar Real Estate  ✅
  + Emak Realestate  ✅
  + Cropleads For Real Estate & investment  ✅
  + Soul Properties  ✅
  + Beyoot  ✅
  + Buyoot For Real Estate  ✅
  + رويال هاوس  ✅
  + Circles investment  ✅
  + All 90  ✅
  + Pro House  ✅
  + One Real Estate  ✅
  + Blocks  ✅
  + Apex Real Estate  ✅
  + One Broker Real Estate  ✅
  + Mavera Property  ✅

========================================
  AGENCIES PAGE 26  →  https://www.propertyfinder.eg/ar/find-broker/search?page=26
========================================
Found 20 agency cards
  + A to Z  ✅
  + Ritzy Developments  ✅
  + Pro-Homes  ✅
  + Make Money  ✅
  + Host Real Estate  ✅
  + Strive Reality  ✅
  + Golden Vision  ✅
  + KMG Real Estate  ✅
  + Royal Hub Real Estate  ✅
  + Elira Real estate Experts  ✅
  + Town River  ✅
  + AL Baroon  ✅
  + Home Sweet Home RE  ✅
  + TPV  ✅
  + Fam Egypt  ✅
  + AMAKEN Misr  ✅
  + عقارات حماد  ✅
  + MADAEN GROUP  ✅
  + Top Cairo Real Estate  ✅
  + Second Home Real Estate  ✅

========================================
  AGENCIES PAGE 27  →  https://www.propertyfinder.eg/ar/find-broker/search?page=27
========================================
Found 20 agency cards
  + Novus Stanza  ✅
  + Upgrade Real Estate.  ✅
  + Bond & Key  ✅
  + ملكي للاستثمار العقاري  ✅
  + Grey Parrot Realty  ✅
  + Emaar Prime X  ✅
  + City One  ✅
  + Osoul Residence  ✅
  + Landpeak Real Estate inv & Marketing  ✅
  + Diyar  ✅
  + Shamy Real Estate  ✅
  + Bold Nest  ✅
  + Marketing Plan  ✅
  + Best Deal For Real Estate  ✅
  + Wnsta how  ✅
  + Cairo Gate Real Estate  ✅
  + Al Beltagy Real Estate  ✅
  + Pylon investment  ✅
  + شركة أويسيز للتسويق العقاري  ✅
  + Badr Homes  ✅

========================================
  AGENCIES PAGE 28  →  https://www.propertyfinder.eg/ar/find-broker/search?page=28
========================================
Found 20 agency cards
  + Foton Real Estate  ✅
  + IHouse development  ✅
  + Nour Eldein for Real Estate  ✅
  + آل المصري جروب  ✅
  + Find House Group  ✅
  + Pyramids for real estate  ✅
  + Relax Red Sea  ✅
  + Envigo Real Estate  ✅
  + SAMA Real Estate Investment  ✅
  + الهدى للمقاولات  ✅
  + TARGET REAL ESTATE  ✅
  + Q VISION  ✅
  + Elite House.  ✅
  + Home Approach  ✅
  + Alabtal Developer  ✅
  + My Real Estate  ✅
  + Capital Broker  ✅
  + Cairo House Real Estate  ✅
  + DOT HOME  ✅
  + أصول دوت كوم  ✅

========================================
  AGENCIES PAGE 29  →  https://www.propertyfinder.eg/ar/find-broker/search?page=29
========================================
Found 20 agency cards
  + White House RE  ✅
  + المؤسسة العقارية للإستثمار والتسويق العقاري  ✅
  + Shenouda Besheer Group  ✅
  + Broker Egypt  ✅
  + Hk Realestate  ✅
  + The Brokerage Hub  ✅
  + العامر للتسويق العقاري  ✅
  + MA Ville  ✅
  + أبو ظبي العقارية  ✅
  + القرش جروب - Elkersh Group  ✅
  + New Build Developments  ✅
  + Pro Master Real estate  ✅
  + El Massa Real Estate  ✅
  + TG West Realtor  ✅
  + Al Ofok Investment  ✅
  + الرضوان العقاريه  ✅
  + تنمية لإدارة المشروعات العقارية  ✅
  + مكتب الساعة للعقارات  ✅
  + New Home Investment  ✅
  + الاستثمار المصري  ✅

========================================
  AGENCIES PAGE 30  →  https://www.propertyfinder.eg/ar/find-broker/search?page=30
========================================
Found 20 agency cards
  + Ring Road Real Estate  ✅
  + Emerald Estates - Egypt  ✅
  + Aqar Share  ✅
  + Diyar real estate development  ✅
  + TiL Real Estate  ✅

,agency_name,agency_logo
0,Coldwell Banker Wealth,https://static.shared.propertyfinder.eg/media/...
1,Selection Code,https://static.shared.propertyfinder.eg/media/...
2,Square real estate,https://static.shared.propertyfinder.eg/media/...
3,New Avenue Real Estate,https://static.shared.propertyfinder.eg/media/...
4,Master Mind Real Estate Services,https://static.shared.propertyfinder.eg/media/...
5,Spade consultancy,https://static.shared.propertyfinder.eg/media/...
6,Egypt Best Properties,https://static.shared.propertyfinder.eg/media/...
7,IRTKAZ,https://static.shared.propertyfinder.eg/media/...
8,Select for real estate,https://static.shared.propertyfinder.eg/media/...
9,Property Hills Star,https://static.shared.propertyfinder.eg/media/...

In [12]:
agencies_df.tail(10)

,agency_name,agency_logo
799,الحسين للاستثمار العقاري,https://static.shared.propertyfinder.eg/media/...
800,One Way For Real Estate,https://static.shared.propertyfinder.eg/media/...
801,البوابة المصرية الأولى,https://static.shared.propertyfinder.eg/media/...
802,INVESTORIA,https://static.shared.propertyfinder.eg/media/...
803,Real Solutions,https://static.shared.propertyfinder.eg/media/...
804,المدينة المنورة للتسويق العقاري,https://static.shared.propertyfinder.eg/media/...
805,الصفا والمروة للتسويق العقاري,https://static.shared.propertyfinder.eg/media/...
806,White House,https://static.shared.propertyfinder.eg/media/...
807,El Swisy Real Estate,https://static.shared.propertyfinder.eg/media/...
808,M W Real Estate,https://static.shared.propertyfinder.eg/media/...

In [14]:
#save to CSV
agencies_df.to_csv("propertyfinder_agencies.csv", index=False)

## Cell 4 — Scrape Sale Listings
Scrapes pages **1 through MAX_PAGES** (now **30**) from Property Finder Egypt's Sale search results.
- `agency_logo` column stores the **broker logo URL**.
- `agency_name` is matched from the agencies DataFrame.
- `publish_date` / `publish_time` are computed from Arabic relative-time strings (Cairo TZ).
- All gallery images are captured (not just 3).
A seen-URLs guard stops if the site repeats the same listings.

In [5]:
# ── Settings ──────────────────────────────────────────────────────
PROPERTYFINDER_SALE_URL = "https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr"
MAX_PAGES               = 50         
# ──────────────────────────────────────────────────────────────────


CAIRO_TZ = pytz.timezone("Africa/Cairo")


def parse_arabic_relative_date(text):
    """
    Convert an Arabic relative-date string to a Cairo-localised datetime.

    Recognised patterns (examples):
        نُشِر منذ 30 دقيقة   → subtract 30 minutes
        نُشِر منذ 2 ساعات    → subtract 2 hours
        نُشِر منذ 5 أيام     → subtract 5 days
        نُشِر منذ أسبوع      → subtract 1 week
        نُشِر منذ 3 أسابيع   → subtract 3 weeks
        نُشِر منذ شهر        → subtract 1 month  (~30 days)
        نُشِر منذ 2 شهور     → subtract 2 months (~60 days)
        نُشِر منذ سنة        → subtract 1 year   (~365 days)
        نُشِر منذ 2 سنوات    → subtract 2 years  (~730 days)

    Returns (publish_date, publish_time) strings, e.g. ("11.06.2026", "10:00 AM").
    Returns (None, None) if parsing fails.
    """
    if not text:
        return None, None

    now_cairo = datetime.now(CAIRO_TZ)

    UNIT_MAP = [
        (r"دقيق",                  "minutes"),
        (r"ساع",                   "hours"),
        (r"يوم|أيام|يومان",        "days"),
        (r"أسبوع|أسابيع",          "weeks"),
        (r"شهر|شهور|أشهر",         "months"),
        (r"سنة|سنوات|عام|أعوام",   "years"),
    ]

    number_match = re.search(r"(\d+)", text)
    number = int(number_match.group(1)) if number_match else 1

    delta = None
    for pattern, unit_key in UNIT_MAP:
        if re.search(pattern, text):
            if unit_key == "months":
                delta = timedelta(days=30 * number)
            elif unit_key == "years":
                delta = timedelta(days=365 * number)
            else:
                delta = timedelta(**{unit_key: number})
            break

    if delta is None:
        return None, None

    pub_dt    = now_cairo - delta
    pub_date  = pub_dt.strftime("%d.%m.%Y")
    pub_time  = pub_dt.strftime("%I:%M %p")   # e.g. "10:00 AM"
    return pub_date, pub_time


def scrape_propertyfinder(base_url, listing_type, max_pages=MAX_PAGES):
    """
    Scrape property listings from Property Finder Egypt using URL-based pagination.

    Property Finder appends &page=N to the base search URL.
    Page 1  → https://…/search?...&page=1
    Page N  → https://…/search?...&page=N

    Parameters
    ----------
    base_url     : str  – Property Finder search URL (no page param)
    listing_type : str  – "Sale" or "Rent" (stored in the listing_type column)
    max_pages    : int  – Maximum number of pages (None = scrape until end)

    Returns
    -------
    pd.DataFrame with columns:
        title, price, location, property_type, bedrooms, bathrooms, area,
        listing_type, agency_logo, agency_name, publish_date, publish_time,
        listing_url, image_urls, source
    """
    driver       = get_driver()
    all_listings = []
    seen_urls    = set()

    # Build a logo→name lookup dict from agencies_df (if available)
    logo_to_name = {}
    try:
        if not agencies_df.empty:
            logo_to_name = dict(zip(agencies_df["agency_logo"], agencies_df["agency_name"]))
    except NameError:
        pass  # agencies_df not yet scraped — agency_name will be None

    for page in range(1, (max_pages or 9999) + 1):
        page_url = f"{base_url}&page={page}"

        print(f"\n{'='*40}")
        print(f"  {listing_type.upper()} PAGE {page}  →  {page_url}")
        print(f"{'='*40}")

        driver.get(page_url)

        try:
            WebDriverWait(driver, 20).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, 'article[data-testid="property-card"]'))
            )
        except Exception:
            print("⚠️  Timed-out waiting for cards — stopping.")
            break

        time.sleep(2)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)

        cards = driver.find_elements(By.CSS_SELECTOR, 'article[data-testid="property-card"]')
        print(f"Found {len(cards)} cards")

        if not cards:
            print("⚠️  No cards found — stopping.")
            break

        new_on_page = 0
        for idx, card in enumerate(cards):
            try:
                try:
                    listing_url = card.find_element(By.CSS_SELECTOR, 'a[data-testid="property-card-link"]').get_attribute("href")
                except Exception:
                    listing_url = None

                if listing_url and listing_url in seen_urls:
                    continue
                if listing_url:
                    seen_urls.add(listing_url)
                    new_on_page += 1

                try:
                    title = card.find_element(By.TAG_NAME, "h3").text.strip()
                except Exception:
                    title = None

                try:
                    price = card.find_element(By.CSS_SELECTOR, '[data-testid="property-card-price"]').text.strip()
                except Exception:
                    price = None

                try:
                    location = card.find_element(By.CSS_SELECTOR, '[data-testid="property-card-location"] p').text.strip()
                except Exception:
                    location = None

                try:
                    property_type = card.find_element(By.CSS_SELECTOR, '[data-testid="property-card-type"]').text.strip()
                except Exception:
                    property_type = None

                try:
                    bedrooms = card.find_element(By.CSS_SELECTOR, '[data-testid="property-card-spec-bedroom"]').text.strip()
                except Exception:
                    bedrooms = None

                try:
                    bathrooms = card.find_element(By.CSS_SELECTOR, '[data-testid="property-card-spec-bathroom"]').text.strip()
                except Exception:
                    bathrooms = None

                try:
                    area = card.find_element(By.CSS_SELECTOR, '[data-testid="property-card-spec-area"]').text.strip()
                except Exception:
                    area = None

                # ── agency_logo: broker logo image URL ─────────────────────────
                try:
                    agency_logo = card.find_element(
                        By.CSS_SELECTOR,
                        'div[data-testid="property-card-broker-logo"] img[data-testid="gallery-picture"]'
                    ).get_attribute("src")
                except Exception:
                    agency_logo = None

                # ── agency_name: matched from agencies_df logo lookup ───────────
                agency_name = logo_to_name.get(agency_logo) if agency_logo else None

                # ── publish_date / publish_time from Arabic relative text ────────
                try:
                    raw_publish = card.find_element(By.CSS_SELECTOR, "footer p").text.strip()
                except Exception:
                    raw_publish = None

                publish_date, publish_time = parse_arabic_relative_date(raw_publish)

                # ── image_urls: ALL gallery images (not just 3) ─────────────────
                try:
                    gallery_container = card.find_element(By.CSS_SELECTOR, '[data-testid="gallery"]')
                    driver.execute_script(
                        "arguments[0].scrollIntoView({block: 'center'});",
                        gallery_container
                    )
                    time.sleep(0.3)

                    gallery_imgs = card.find_elements(
                        By.CSS_SELECTOR,
                        '[data-testid="gallery"] img[data-testid="gallery-picture"]'
                    )
                    image_urls_list = []
                    for img in gallery_imgs:
                        src = img.get_attribute("src") or img.get_attribute("data-src")
                        if src and "placeholder" not in src and src not in image_urls_list:
                            image_urls_list.append(src)

                    image_urls = "|".join(image_urls_list) if image_urls_list else None
                except Exception:
                    image_urls = None

                all_listings.append({
                    "title":          title,
                    "price":          price,
                    "location":       location,
                    "property_type":  property_type,
                    "bedrooms":       bedrooms,
                    "bathrooms":      bathrooms,
                    "area":           area,
                    "listing_type":   listing_type,
                    "agency_logo":    agency_logo,
                    "agency_name":    agency_name,
                    "publish_date":   publish_date,
                    "publish_time":   publish_time,
                    "listing_url":    listing_url,
                    "image_urls":     image_urls,
                    "source":         "Property Finder Egypt",
                })

                short_title = (title[:65] + "...") if title and len(title) > 65 else (title or "Unknown")
                print(f"  {idx+1:>3}. {short_title}")

            except Exception as e:
                print(f"  ⚠️  Card {idx+1} error: {e}")

        if new_on_page == 0:
            print("\n🏁 No new listings on this page — scraping complete.")
            break

    driver.quit()

    df = pd.DataFrame(all_listings)
    print(f"\n✅ {listing_type} scraping done — {len(df)} listings collected")
    return df


# ── Run ───────────────────────────────────────────────────────────
sale_df = scrape_propertyfinder(PROPERTYFINDER_SALE_URL, "Sale")
sale_df.head()

========================================
  SALE PAGE 1  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=1
========================================
Found 25 cards
    1. فيلا TYPE D ب اسكارليت استلام فوري باقساط بحري
    2. امتلك تاون هاوس ع10سنين تلال إيست متشطب بالتكيفات
    3. تاون هاوس استلام فوري موقع مميز ف سوان ليك ريزيدنس
    4. ستند الون فيلا استلام فوري موقع مميز في سوان ليك
    5. فيلا بموقع مميز للبيع في سوان ليك ريزيدنس
    6. تاون هاوس بسعر مميز متشطب بالكامل ماونتن فيو
    7. شاليه مميز للبيع باقساط متشطب بالكامل مزارين
    8. شاليه باقساط للبيع جون الساحل الشمالي
    9. فيلا مميزة تطل علي البحر للبيع هاسيندا باي الساحل
   10. شقة ارضي153م+82م جاردن متشطبة بالتكييفات فقلب زايد
   11. شاليه للبيع هاسيندا باي متشطب بالكامل باقساط
   12. شاليه مميز جاهز أرضي بجاردن سوان ليك Best Deal
   13. فيلا للبيع فوكا باي الساحل الشمالي مفروشة بالكامل
   14. فيلا مميزة جاهزة واجهة بحري سوان ليك Best Deal
   15. توين هاوس مميز بحري فرصة نادرة سوان ليك Best Price
   16. شاليه مميز مع رووف كبير بحري علي اللاجون BEST DEAL
   17. فيلا مستقلة فاخرة للبيع بالم هيلز قطاميه
   18. شقة متشطبة ريسيل فى ايست فالى سوديك بالسعر القديم
   19. شاليه 126م ريسيل فى ذا ميد الساحل تكملة اقساط 2031
   20. امتلك شاليه بالساحل الشمالي تقسيط وعلينامصيفك هديه
   21. توين هاوس ريسيل فى ازها الساحل تكمله اقساط 2031
   22. شقة غرفتين متشطبه بالتكيفات + المطبخ استلام فوري
   23. فيلا للبيع في هايد بارك في موقع مميز وتشطيب كامل
   24. توين هاوس للبيع - فيو مميز - فى سيتى جيت بسعر مميز
   25. استلام قريب 3غرف للبيع في زد ويست متشطبة بالكامل

========================================
  SALE PAGE 2  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=2
========================================
Found 25 cards
    1. شاليه 3غرف علي البحر دايركت للبيع في جون متشطبة
    2. شقة متشطبة بالمطبخ و التكييفات بمقدم ديستركت 5
    3. أكبر توين هاوس تشطيب سوبر لوكس في ليان بفيو مفتو ح
    4. لسرعة البيع سكاى لوفت متشطب بالكامل باقل سعر بمقدم
    5. تاون هاوس متشطب مفروش بالكامل و السعر قابل للتفاوض
    6. شقه في فيليت سوديك متشطبه بالتكيفات في موقع متميز
    7. كواترو استلام فوري في موقع مميز السعر قابل للتفاض
    8. دوبلكس روف للبيع في جايد متشطب بالكامل بمقع متميز
    9. اقل من سعر السوق توين هاوس استلام فوري بڤيو مميز
   10. شقة متشطبة بالتكيفات و المطبخ للبيع في المراسم
   11. شقة ارضي متشطبة سوبر لوكس موقع مميز و استلام فوري
   12. أقل سعر شقة متشطبة سوبر لوكس للبيع فى موقع متميز
   13. تاون هاوس للبيع علي ڤيو مفتوح اقل من سعر السوق
   14. شقة أرضية فاخرة بالتقسيط بحديقة 160 متر
   15. شقة كاملة التشطيب موقع مميز فيو لاندسكيب و نافوره
   16. آقل سعر تاون كورنر في تاج سيتى فيو مساحات خضراء
   17. شقه للبيع استلام فوري في بلوم فيلدز المستقبل سيتي
   18. شقة غرفتين تشطيب كامل بموقع متميز ليك فيو ريزيدنس
   19. بسعر مميز شقة كورنر متشطبة بالتكييفات في بالم هيلز
   20. شقة مميزه للبيع مفروشه بالكامل استلام فوري
   21. جولف بورتو مارينا واستمتع مع أكبر خصم لأول مره 53%
   22. بأفضل إطلالة مع أكبر خصم يُقدَّم لأول مرة بجولف
   23. ستوديو 56 م² – مارينا الجديدة- 0% مقدم | 10 سنوات
   24. ادفع 5% وامتلك شاليه متشطب فى JEFAIRA
   25. عرض الكاش المتقسط مع خصم 50%

========================================
  SALE PAGE 3  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=3
========================================
Found 25 cards
    1. Golf Porto Marina Cash Units | Prime Views
    2. فرصة استثمار قوية لشقق 60م كاش
    3. امتلك شاليهك 60م بأفضل سعر كاش|في الجولف
    4. شاليه ريسيل متشطب بالكامل للبيع في سيلفر ساندز
    5. بلايا غزالة شاليه أرضي ( كومبلكس ) استلام فوري
    6. بنتهاوس للبيع في Makadi Heights البحر الأحمر
    7. شقة 210م للبيع ريسيل استلام فوري في ذا سكوير
    8. باقل من سعر السوق توين هاوس بتشطيب سوبر لوكس 291م
    9. شاليه ارضي للبيع بموقع مميز في هاسيندا ويست غرفتين
   10. بنتهاوس للبيع بمساحات نادرة
   11. ريسيل توين هاوس في تيرازو ألمازا باي | استلام 2027
   12. قصر صف أول علي البحر ٨غرف ماستر بشاطئ خاص
   13. فيلا مساحه صف اول ع الجولف
   14. شقه لقطه 182 استلم فورى ودبل فيو
   15. فيلا 165م بمقدم واقساط استلم خلال سنه 3غرف 3 حمام
   16. تاون هاوس4 غرف بمقدم 12مليون في اجدد مراحل ابتاون
   17. وحدة مميزة للبيع برووف خاص
   18. شقة مميزة في أرقى لوكيشن داخل فاي سوديك
   19. فيلا بحمام سباحه مميز علي جاردن للبيع بأقل سعر
   20. شقه اقل من سعر السوق بموقع مميز 113 متر
   21. تاون هاوس للبيع ف اب تاون كايرو للبيع
   22. اقل سعر شاليه مطل علي البحر بمقدم 5% علي 10 سنين !
   23. شاليه غرفة بإطلالة بحرية في Glee الساحل الشمالي
   24. شاليه بإطلالة مباشرة على اللاجون تشطيب بالتكيفات
   25. شاليه بجاردين جاهز للاستلام مباشر علي اللاجون

========================================
  SALE PAGE 4  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=4
========================================
Found 25 cards
    1. باقل سعر فيلا استلام فوري 368م في لافيستا - فرصة
    2. فرصة استثنائية لامتلاك شقة في فاي سوديك
    3. فيلا مستقلة 3 غرف 290م | ريحان فيلاز التجمع الأول
    4. بأقل سعر شالية غرفتين بمنتجع بورتو السخنة البهامز
    5. فيلا بسعر مميز للبيع على اقساط حتى 2028 في بيل فيي
    6. أميز شقة كورنر في فيلدج ويست بأفضل مساحة
    7. وحدات بأقل سعر متر في شمال الرحاب استلام فورى
    8. توين شاليه بإطلاله على البحر استلام سنه و بمقدم 5%
    9. شاليه مطل على اللاجون | استلام قريب | مقدم 5% فقط
   10. شاليه فيو بحر بالفرش والاجهزه للبيع في فوكا باي
   11. شالية جاهز للاستلام اقل من سعر الماركت فيو لاجون
   12. إطلالة، موقع، وسعر لا يتكرر في فيلدج ويست
   13. للبيع شاليه 100 م عالبحر - البانوراما بورتو السخنة
   14. شاليهك 2نوم بسعر لقطه مع كونكورد السلام بالسخنة
   15. فرصة استثمارية مميزة – آي فيلا في آي سيتي أكتوبر
   16. اقل سعر شالية 3نوم بالعلمين الجديده بأقساط10سنين
   17. شقة لقطة للبيع فى اللوتس الشمالية التجمع الخامس
   18. شاليه للبيع بتشطيب فندقي علي البحر مباشرة بالساحل
   19. اقل سعر شقة ٣ غرف نوم افضل موقع علي حديقة ١٧٠ متر
   20. فيلا ٦ غرف متشطبه بالكامل للبيع في ماراسي باي
   21. أفضل سعر 3 غرف نوم 200 متر تشطيب كامل ميفيدا اعمار
   22. فيلا بحمام سباحه للبيع باقل من سعر الماركت
   23. شقة متشطبه للبيع في بالم هيلز القاهرة الجديدة كليو
   24. أفضل سعر بنتهاوس 192م رووف 110م بحري موقع مميز
   25. فرصة مميزة لامتلاك شقة بحري كورنر في آي سيتي

========================================
  SALE PAGE 5  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=5
========================================
Found 25 cards
    1. استلم فوري شاليه متشطب بالتكييفات بأقل مقدم 3 م
    2. شاليه للبيع في بورتو السخنة – الكاريبيان باي 2
    3. تاون هاوس استلام قريب ب سوديك نيو زايد ب اقل سعر
    4. استلام فورى تري البحر متشطبه و مفروشه تاني صف بحر
    5. كورنر فيو مفتوح تطل جزئياً على البحيرة الصناعية
    6. شقه بحرى متشطبه بالتكييفات فى al burouj موقع مميز
    7. آخر شقة 164م متشطبة-باتيو أورو-3مليون مقدم
    8. للبيع شاليه ريسيل مميز في مارسيليا بيتش 3
    9. ستوديو بجاكوزي|ماونتن فيو| أورورا بالاس
   10. شقة حديثة غرفة نوم واحدة للبيع في أورورا بالاس
   11. وحدة للبيع في سموحة بمروج تشييد موقع مميز
   12. وحدة للبيع في سموحة بمروج تشييد موقع مميز
   13. فيلا متشطبة للبيع في التجمع الخامس بسعر مميز
   14. فيلا مستقلة متشطبة بالكامل بسعر مميز من سوديك
   15. امتلك شقة متشطبة مساحة 165م ب6اكتوبر من اورسكوم
   16. شاليه بحري 3غرف بفيو لاجون بالعين السخنه بمقدم10%
   17. بالتقسيط استلام شقه بتراس2غرف متشطبه للبيع او ويست
   18. ستوديو للبيع في أورورا بالاس| 73م² بول فيو
   19. مودرن فيلا مستقلة استلام فوري تشطيب 70%
   20. شقة فندقية بشاطئ خاص واستلام فوري
   21. امتلك شقة غرفتين بإطلالة بول فيو في أورورا بالاس
   22. ستوديو 80م² للبيع في أورورا بالاس جاكوزي خاص
   23. ڤيلا كامله الفرش والتشطيب في The Scarlet – SLR
   24. ستوديو 68م² للبيع في أورورا بالاس مع جاكوزي خاص
   25. شقة غرفة نوم 91م² بول فيو للبيع في أورورا بالاس

========================================
  SALE PAGE 6  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=6
========================================
Found 25 cards
    1. ستوديو 73م² بول فيو للبيع في أورورا بالاس
    2. ستوديو 70م² بول فيو للبيع في أورورا بالاس
    3. للبيع تاون هاوس ميدل علي حمام السباحة - ريفا فيوز
    4. شقتك 2نوم للبيع بمقدم5%فقط بالتجمع بأقساط10سنين
    5. شقه 3غرف علي أعلي نقطه بالتجمع السادس بمقدم5%
    6. استلام فوري اقل سعر شقه بجاردن للبيع في فاي سوديك
    7. استلم شقة 200م فوري متشطبة بالتكييفات والسعر لقطه
    8. اي فيلا روف مميزة استلام فوري بأقل سعر في الماركت
    9. شقه جنب مول العرب بمقدم 400,000 وقسط شهري 6,000
   10. شاليه متشطب+التكيفات منORAمقدم مليون ونص قسط 8سنين
   11. استلم فورا شقه متشطبه 150م+112م جاردن و قسط 7سنين
   12. تاون هاوس استلام فوري يطل علي مساحات خضراء - اعمار
   13. شقه بجاردن متشطبه 130م+50م جاردن استلام فوري+قسط
   14. شاليه جاهز للسكن في قلب مدينة العلمين فيو مسبح
   15. شقه بجاردن متشطبه 130م+50م جاردن استلام فوري+قسط
   16. شاليه 130م باقل مقدم و اقساط علي 8 سنوات - سي شور
   17. استلم فورا شقه ف كمبوند فاخر 7,276,000 و متاح قسط
   18. 110م بسهر اللونش فيو لاجون300م من البحر قسط 10سنين
   19. شقه 147م+70م جاردن متشطبه من بالم هيلز بقسط ع12سنه
   20. شاليه 150م استلام فوري سي فيو بمقدم و اقساط
   21. شقة مميزة بأقل سعر وموقع استراتيجي في هايد بارك
   22. شقة متشطبة بالتكييفات بسعر وفيو وموقع مميزين
   23. توين هاوس 530م موقع مميز بحري استلام فوري
   24. فيو كامل للبحر شاليه محدود في جون سوديك -باقل سعر
   25. شقه استلام فوري 170متر فيو لاند سكاب للبيع - VGK

========================================
  SALE PAGE 7  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=7
========================================
Found 25 cards
    1. اقل من سعر الماركت - تاون هاوس للبيع -PK1
    2. فيلا 355م بموقع مميز جدا للبيع في سعاده
    3. تاون هاوس كورنر للبيع على البحيرة 4 غرف في سول
    4. اقل مقدم فيلا Z1 استلام فورى للبيع فى باديه اكتوبر
    5. استلم فوري شقة متشطبة مساحة 180م بالشيخ زايد
    6. شقة فاخرة للبيع بالقاهرة الجديدة بتشطيب كامل
    7. اقل سعر شاليه متشطب+تكيفات فى الساحل-تقسيط 8 سنين
    8. شقة أرضي بحديقة خاصة للبيع في الياسمين 8 – القاهرة
    9. شقة 3 غرف 160م | ذا أدرس إيست التجمع الخامس
   10. شالية بفيو الجولف والبحيرات 65م جاهز فالسخنة
   11. استوديو استثماري مميز للبيع في الداو هايتس
   12. 3غرف استلام فوري هايد بارك التجمع الخامس بالتقسيط
   13. شاليه للبيع (بورتو جولف)
   14. شالية مفروش للبيع في الحدائق المعلقة- بورتو السخنه
   15. ماونتن فيو اي سيتي اي فيلا بروف متشطبة استلام فورى
   16. شقة بتشطيب راقي - فرصه للاستثمار - بسعر لقطة
   17. استلم الآن 93م غرفتين في لاندمارك بقسط 18,600شهريا
   18. أقل سعر ارضي بجاردن بالشيخ زايد امام هايبر قسط 10س
   19. تجربة سكن راقية بإطلالة وخصوصية في لافيستا سيتي
   20. للبيع شاليه استلام فوري مرحلة اهرامات بورتو السخنة
   21. امتلك شقة غرفتين مع بول فيو في أورورا بالاس
   22. غرفة نوم واحدة للبيع في أورورا بالاس مع بول فيو
   23. شاليه متشطب بسعر محروق بتكملة اقساط برايم لوكشن
   24. شاليه مفروش للبيع يرى البحر -بهامز بورتو السخنه
   25. شاليه مفروش فيو بانوراما بحر بالحدائق المعلقة

========================================
  SALE PAGE 8  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=8
========================================
Found 25 cards
    1. استلم فورا 152م+حديقة نص سنوى660 ألف أوكاش5.500.00
    2. شقة محدودة في سوديك بفيو مفتوح اقل من الماركت
    3. شقة استلام فوري - متشطب بالكامل - باركنج
    4. استلم فورا شاليه3غرف+جارجن245م سى فيو بالتقسيط 10س
    5. فيلا مميزه جدا للبيع استلام فوري من اعمار مصر
    6. فيلا لقطة للبيع في قلب مدينة 6 اكتوبر بالتقسيط
    7. شقق استلام فوري في حدايق اكتوبر
    8. اخر فيلا 305م² بجوار النادي تطل علي لاند اسكيب،قسط
    9. استلم فوري تاون هاوس متشطب ماونتن فيو أكتوبر بارك
   10. اقل مقدم فيلا 4نوم برايم لوكيشن ف سعادة
   11. فيلا فاخرة استلام فوري، بحمام سباحة - قسط ٨ سنوات
   12. شقة متشطبة بالتكيفات أستلام شهور كمبوند الكارما
   13. شاليه باقل سعر - صف اول، سي فيو، متشطب، قسط١٠سنوات
   14. شقة بشاطئ خاص واطلالة بحر وحمام سباحة استلام فوري
   15. شقة بجاردن متشطبة بالتكيفات في قلب زايد، باقل سعر
   16. للبيع شاليه تشطيب وفرش حديث -الهاواين بورتو السخنة
   17. فيلا ONE STORY جاهزة للاستلام بأمكانية التقسيط
   18. فيلا واجهة للبيع بحدائق الاهرام موقع ممتاز 250 م
   19. 107م بجاردن فيو مفتوح قسط ربع سنوي 71K لمدة 108شهر
   20. شاليه مودرن متشطب بالتكييفات فى هاسيندا رأس الحكمة
   21. شاليه متشطب بالكامل للبيع في لافيستا 185متر
   22. شقه في جايد مع حديقه خاصه للبيع بأقل سعر في السوق
   23. تربلكس محدود في لوكيشن مميز سوديك ايستاون اقل سعر
   24. شقة اقل من الماركت محدودة في ايستاون سوديك متشطبة
   25. شقة بجاردن-ايستاون سوديك-قريبة جدا لجاكاراندا بارك

========================================
  SALE PAGE 9  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=9
========================================
Found 25 cards
    1. شقة متشطبة اقل من الماركت ريسيل فوري في vye سوديك
    2. تاون هاوس165م بالمستقبل سيتي مقدم5% قسط علي 10سنين
    3. شاليه متشطب فى سوما باى أقل مقدم قسط 8سنين
    4. شاليه متشطب بالكامل موقع مميز في بلايا علي اللاجون
    5. فيو جاردن شقه للبيع في ميفيدا التجمع الخامس
    6. اميز شقه للبيع فى ميفيدا بفيو حمام سباجه
    7. شقه ريسيل في باديه غرفتين باقل سعر استلام فوري
    8. شقة بحديقة 300م 3/4 تشطيب للبيع ريسيل - ذا سكوير
    9. شقة 173م استلام فوري متشطبة بستودا قسط علي 10 سنين
   10. شقة للبيع بالباتيو سولا بمقدم 400 الف و قسط علي 8س
   11. شالية فاخر في June Sodic مقدم 10% و قسط 10سنين
   12. شقه متشطبه ومتسلمه بالتكيفات استلام فوري بالتقسيط
   13. أستلم حالا فيلتك متشطبه ع طريق مصر اسكندريه 0%مقدم
   14. شالية فوري مجهز سوبر لوكس بالكامل 62م بحري صريح !
   15. بالفيو الروعه دا هتستلم شاليهك فورا مجهز 100م بحري
   16. فرصة شالية بالسعر القديم 110م ارضي فيو روعه
   17. بأقل من مليون ونص! شاليه فالجولف 65م دور متكرر
   18. لقطه للبيع شقة 3نوم بأقل سعر بغرب الجولف بالتجمع
   19. لو بتدور على الرقي .. هتلاقيه في مروج
   20. امتلك فيلتك بطابع يوناني وإطلالة لا تُنسى
   21. استلم شاليهك في خلال سنة متشطب بالفرش
   22. شاليه ريسيل استلام فوري لاجون فيو اقل اوفر للماركت
   23. استوديو فندقي بعرابيا | استلام 2026 | تقسيط 4 سنين
   24. الفيلا دي مش مجرد عقار ... دي نقلة حياة
   25. شاليهك 2نوم متشطب فى الداون تاون بتقسيط 12 سنة

========================================
  SALE PAGE 10  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=10
========================================
Found 25 cards
    1. الفخامة بقت أقرب… والسداد بقى أسهل
    2. شقه مميزة للبيع بالتقسيط حتي 2031 لايك فيو ريذيدنس
    3. شقة بأقساط مميزة للبيع في لايك فيو ريزيدنس 2
    4. تاون هاوس 3غرف فيو مفتوح استلام فوري بسعر لقطه
    5. افتح باب حياة جديد .. لسكن يليق بيك
    6. بمقدم 1% استلم فورا شقة متشطبة بالعاصمة بقسط15سنة
    7. شاليه 2نوم لاجون فيو استلام فوري بأقساط حتي10سنين
    8. شاليه دوبلكس للبيع في مورانو –فيو حمام سباحة
    9. للبيع شقة 190م واجهه تشطيب فندقي بسعر مميز جدا
   10. تاون هاوس للبيع في ماونتن فيو تشيل أوت بارك
   11. شقة لمحبي الاستثمار بأقل سعر دقائق من AUC بالتجمع
   12. عرض لفترة محدودة شقتك 3نوم بأقل سعر بالتجمع
   13. اقل سعر شقة 3نوم بجوار Hyde Park بالتجمع الخامس
   14. شاليهك بحري سي فيو بـأقـل سـعـر بالساحل وبالتقسيط
   15. توين هاوس في ميفيدا متشطب بالكامل استلام فوري
   16. شقة غرفتين جاهزة للسكن بأقل سعر وإطلالة مفتوحة.
   17. وحده 60 متر غرفتين بفيو بحري على البول استلام قريب
   18. شقتك ارضي بـ7,9 مليون كاش او ادفع مليون قسط سنوي
   19. مرحلة جديدة بأسعار طرح لفترة محدودة شاليهات الساحل
   20. شقة للبيع في التجمع الخامس غرب الجولف
   21. شاليه 60م على الاكوا بسعر كاش 1,750,000ج
   22. امتلك بنتهاوس باطلالة كاملة على البحر وقسط حتى 10س
   23. فيلا استلام فوري في سوديك لوكيشن مميز بسعر لقطه
   24. للبيع شالية 67 mثاوث ميد بدون اوفر
   25. ب400 الف مقدم استلم شاليه متشطب فى مزارين العلمبن

========================================
  SALE PAGE 11  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=11
========================================
Found 25 cards
    1. ريسيل دوبليكس كورنر في زد باقل سعر و لوكيشن مميز
    2. بأقل سعر للبيع شاليه 130متر+روف130متر بأميز موقع
    3. فيلا استلام فوري امام مطار سفنكس في ذا استيس سوديك
    4. توين هاوس بحري - صف اول علي اللاجوون - سوان ليك
    5. شاليه كامل التشطيب | 20 ألف شهريًا | جاهز للاستلام
    6. شاليه للبيع في أزها العين السخنة – فيو حمام سباحة
    7. شقة 80م لقطة للبيع- كمبوند دجلة بالمز - اكتوبر
    8. استلام فوري - تاون كورنر بحري - صف اول - سعر لقطة
    9. ارخص كوترو فيلا ف الماركت في كايرو فيستفال سيتي
   10. شقة ٣ غرف أقل من سعر السوق موقع مميز استلام فوري
   11. ادفع 10% وقسط على 96 شهر في 139م بقسط ربع سنوي 98K
   12. شقة 3 غرف بسعر محروق خلف مول العرب تقسيط 10 سنوات
   13. ريسيل فيلا مستقلة اقل من سعر المركت مرحلة الفيلات
   14. مقدم 1.5٪ فقط شقة بالعاصمة بأسعار طرح لفترة محدودة
   15. اقل سعر فيلا ستاند الون كلاسيك هايد بارك التجمع
   16. فيلا جاهزة للسكن للبيع في ذا استيتس بجوار بيفرلي
   17. فيلا جاهزة للاستلام داخل The Estates – Sodic West
   18. توين هاوس للبيع في كمبوند جيدار –أقل سعر
   19. تاون هاوس مميز مساحة 220م لاندسكيب فيو و قسط علي7س
   20. شقة استلام فوري بسعر لوكيشن مميز مباشرة ع لاندسكيب
   21. ريسيل خالصه اقساط بسعر قابل للتفاوض من المالك
   22. اقل سعر شقه 3 غرف استلام فورى للبيع فى MV I-City
   23. للبيع شقة 176م لقطه في اب تاون اكتوبر بتقسيط
   24. بدون اوفر شقة للبيع مع اقساط حتى 2032 في زيد ويست
   25. فيلا للبيع او ويست وايت- اوراسكم

========================================
  SALE PAGE 12  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=12
========================================
Found 25 cards
    1. لقطة أقل سعر للمتر لسرعة البيع بنتهاوس بلاميرادا
    2. تاون هاوس فيو مفتوح موقع مميز في مراسي
    3. توين هاوس على البحيرة مباشرة بموقع مميز
    4. شقة دور اول في كابيتال جاردن ١٦٣ م استلام فوري
    5. توين هاوس بفيو مفتوح في فيرونا مراسي
    6. شقة للبيع فى اويست مرحلة تلوا متشطبة بالكامل
    7. توين هاوس متشطب ف اب تاون كايرو مرحلة اليفا
    8. 3 غرف لوكيشن بحرى بسعر لقطة عرض محدود
    9. شقه تشطيب فاخر وفرش كامل بالتكيفات فيو مفتوح
   10. ادفع10% وقسط على 96 شهر في 163م بقسط ربع سنوي 115K
   11. شقة بأقل سعر في كمبوند بروميناد التجمع الخامس
   12. بمقدم 100 الف جنيه امتلك شاليه في قلب العالمين
   13. فيلا نموذج F للبيع او ويست وايت- اوراسكم
   14. اقل سعر ستديو يطل علي بحر استلام فوري
   15. افضل سعر ڤيلا متشطبة فى مدينتى بموقع متميز
   16. دوبلكس بالفرش بحرى بڤيو على البحر سعر مميز
   17. فيلا فاخرة للبيع في إل باتيو هيلز 255 متر
   18. فيلا للبيع او ويست وايت- اوراسكم
   19. استلم فيلا ع وصلة دهشور مباشرة بأقل مقدم 5 مليون
   20. شقق استلام فوري في قلب التجمع متشطبه بالكامل
   21. اي فيلارووف باقل سعرريسيل بماونتن فيو اي سيتي فوري
   22. ادفع 10% وقسط على 96 شهر في 132م قسط ربع سنوي 102K
   23. فيلا للبيع او ويست وايت- اوراسكم
   24. شاليه متشطب في جون سوديك بمقدم 5% وقسط 10 سنوات
   25. فيلا للبيع ذا استيتس سوديك -موقع متميز

========================================
  SALE PAGE 13  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=13
========================================
Found 25 cards
    1. دور واحد توين هاوس استلام فوري في جون سوديك محدودة
    2. شالية مستقل ارضي مفروش بالكامل للبيع في فوكا باي
    3. اقل سعر شقه مساحه كبيره ماونتن فيو اي سيتي ليك فيو
    4. شقه 3 غرف للبيع في بلوم فيلدز افضل سعر بالماركت
    5. بنتهاوس بإطلالة بحرية ورووف خاص | كالا
    6. شاليه للبيع فى السخنه فى قريه لافيستا توباز 4 نوم
    7. شقه للبيع 137متر تشطيب خرافي بسعر معقول جداا
    8. اب تاون مجاورة الأولي قطاع ٨ اميز سعر اصيل مباشر
    9. كورنر تاون هاوس في تاج سيتي 160م+131جاردن
   10. للبيع شقة130م بالتقسيط ع 12سنهvip view
   11. شاليه عالبحر 3غرف متشطب بالتكييفات ف تلال السخنه
   12. شقه للبيع باقل قسط شهري في سراي بسعر الطرح القديم
   13. شقة للبيع ببرايم لوكيشن ف التجمع الخامس\مقدم 890K
   14. امتلك شاليه متشطب بفيو ع البحر في العين السخنه
   15. شقة غرفتين للبيع ف هايد بارك التجمع\مقدم 475الف
   16. شقة غرفتين للبيع بخصم كبير لفترة محدودة - تاج سيتي
   17. بمقدم 710الف امتلك شقه162م دور متكرر قسط ع12سنه
   18. بمقدم 500الف امتلك شقه قسط ع10سنين ف التجمع الخامس
   19. للبيع – شقة مميزة بكمبوند دجلة بالمز – المرحلة ال3
   20. فيلا للبيع - سوبر لوكس - موقع مميز - 90 الشمالى
   21. روف دبل فيس بغرب أربيلا بتراس كبير واستلام 6 شهور
   22. للبيع شقة 170 في السياحية امام نادي النادي مباشرة
   23. فيلا سعرها وموقعها متميز تطل مباشرة ع لاند سكيب
   24. شاليه مميز ارضي بجاردن في ماونتن فيو السخنة1 كورنر
   25. للبيع - توين هاوس - كمبوند دارا جاردنز

========================================
  SALE PAGE 14  →  https://www.propertyfinder.eg/ar/search?c=1&fu=0&ob=mr&page=14
========================================
Found 25 cards
    1. فيلا للبيع - كمبوند اتريو - الشيخ زايد

,title,price,location,property_type,bedrooms,bathrooms,area,listing_type,agency_logo,agency_name,publish_date,publish_time,listing_url,image_urls,source
0,فيلا TYPE D ب اسكارليت استلام فوري باقساط بحري,٥٣٬٠٠٠٬٠٠٠ جنيه,"سوان ليك ريزيدنس, كمبوندات التجمع الخامس, التج...",فيلا,7+,7+,٦٥٠ متر مربع,Sale,https://static.shared.propertyfinder.eg/media/...,None,10.06.2026,06:48 AM,https://www.propertyfinder.eg/ar/plp/buy/villa...,https://static.shared.propertyfinder.eg/media/...,Property Finder Egypt
1,امتلك تاون هاوس ع10سنين تلال إيست متشطب بالتكيفات,١٥٬٤٩٠٬٠٠٠ جنيه,"تلال إيست, كمبوندات التجمع الخامس, التجمع الخا...",فيلا,3,3,٢٦٢ متر مربع,Sale,https://static.shared.propertyfinder.eg/media/...,None,11.06.2026,03:48 AM,https://www.propertyfinder.eg/ar/plp/buy/villa...,https://static.shared.propertyfinder.eg/media/...,Property Finder Egypt
2,تاون هاوس استلام فوري موقع مميز ف سوان ليك ريز...,٢٦٬٠٠٠٬٠٠٠ جنيه,"سوان ليك ريزيدنس, كمبوندات التجمع الخامس, التج...",تاون هاوس,5,4,٢٤٧ متر مربع,Sale,https://static.shared.propertyfinder.eg/media/...,None,10.06.2026,02:48 PM,https://www.propertyfinder.eg/ar/plp/buy/townh...,https://static.shared.propertyfinder.eg/media/...,Property Finder Egypt
3,ستند الون فيلا استلام فوري موقع مميز في سوان ليك,٣٩٬٠٠٠٬٠٠٠ جنيه,"سوان ليك ريزيدنس, كمبوندات التجمع الخامس, التج...",فيلا,4,5,٣٨٨ متر مربع,Sale,https://static.shared.propertyfinder.eg/media/...,None,10.06.2026,02:48 PM,https://www.propertyfinder.eg/ar/plp/buy/villa...,https://static.shared.propertyfinder.eg/media/...,Property Finder Egypt
4,فيلا بموقع مميز للبيع في سوان ليك ريزيدنس,٤٢٬٠٠٠٬٠٠٠ جنيه,"سوان ليك ريزيدنس, كمبوندات التجمع الخامس, التج...",فيلا,5,4,٤٨٥ متر مربع,Sale,https://static.shared.propertyfinder.eg/media/...,None,10.06.2026,01:48 PM,https://www.propertyfinder.eg/ar/plp/buy/villa...,https://static.shared.propertyfinder.eg/media/...,Property Finder Egypt

## Cell 5 — Scrape Rent Listings
Scrapes pages **1 through MAX_PAGES** (now **30**) from Property Finder Egypt's Rent search results
using the same `scrape_propertyfinder()` function defined above.

In [6]:
# ── Settings ──────────────────────────────────────────────────────
PROPERTYFINDER_RENT_URL = "https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr"
MAX_PAGES               = 50
# ──────────────────────────────────────────────────────────────────


# ── Run ───────────────────────────────────────────────────────────
rent_df = scrape_propertyfinder(PROPERTYFINDER_RENT_URL, "Rent")
rent_df.head()

========================================
  RENT PAGE 1  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=1
========================================
Found 25 cards
    1. فرصة مميزة للإيجار | توين هاوس فاخر في PK1
    2. شقة فاخرة للإيجار في كمبوند ووتر واي | موقع متميز
    3. دور أرضي مفروش مودرن للإيجار في ستون ريزيدانس
    4. هاسيندا وايت دوبلكس أرضى للإيجار 4 غرف وناني
    5. شقة للإيجار جنوب الأكاديمية أ – موقع ذهبي
    6. للإيجار – توين هاوس مميز صف أول جولف في ديونز
    7. شقة مفروشة بالكامل في فيليت سوديك
    8. فرش راقي | شارع ٩ | بجوار المترو
    9. فيلا للايجار بحمام سباحه كمبوند قطاميه ريزدنس
   10. توين هاوس للايجار 4غرف و غرفه في بينتهاوس باقل سعر
   11. اي فيلا رووف للإيجار بسعر مميز في ماونتن فيو
   12. شقة للإيجار في ليك فيو ريزيدنس | 144 متر
   13. شقة نصف مفروشة للإيجار في ميفيدا بلو فيوز | 185 م
   14. شقه للايجار بالمطبخ والتكييفات في النرجس 2 بالتجمع
   15. شقة للإيجار في سوديك إيستاون مساحة كبيرة
   16. إطلالة مفتوحة ورووف واسع لحياة هادئة ومميزة
   17. سنوديو مميز بالمطبخ والتكيفات للايجار في مراسم
   18. استديو مفروش فاخر -للأيجار في هايد بارك
   19. شقة مفروشة فاخرة-160متر-للأيجار في ذا اسكوير
   20. توين هاوس مميز-الترا سوبر لوكس -للايجار في ميفيدا
   21. بنتهاوس مطبخ وتكييفات للايجار في فيفث سكوير
   22. شقه مميزه ارضي بجاردن -بالتكيفات-فيو مميز-ميفيدا
   23. للايجار ق.ج رشدى 175م (متفرع من ش سوريا) .
   24. شقة مميزه ارضي مع جاردن للإيجار في آزاد
   25. شقه نص مفروشه اول سكن قريبه من جميع الكلوب هاوس

========================================
  RENT PAGE 2  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=2
========================================
Found 25 cards
    1. مفروش للايجار فرش فندقي اول سكن قريبه من الليك ديس
    2. شقه مفروشه اول سكن فيو مميز فرش مودرن تشطيب فندقي
    3. للايجار متشطب بالتكيفات فيو مفتوح على الجاردن بحرى
    4. للأيجار دور ثانى متشطبه بالكامل 3 غرف و بحرى
    5. شقة أول سكن مفروشة للايجار ف كمبوند المراسم التجمع
    6. توين هاوس فيلا للإيجار في قطامية ديونز | فيو جولف
    7. مفروش راقي جد اول سكن تشطيب فندقي قريبه من الخدمات
    8. شقة فاخرة بجاردن في ميفيدا كريسنت فيو سنترال بارك
    9. للايجار متشطب بالتكيفات فيو مفتوح على الجاردن بحرى
   10. مفروش فرش مودرن اول سكن تشطيب فندقي موقع مم
   11. شقه للايجار علي الجولف باجهزه المطبخ و التكيفات
   12. شقة2 -نوم- اول استخدام للأيجار بكمبوند لايك فيو
   13. مطبخ بالاجهزة - الترا سوبر لوكس - سعر حاص
   14. شقه مودرن باقل سعر للايجار في كمبوند ميفيدا
   15. شاليه غرفتين ماستر للإيجار في جريك ڤيلدج مراسي
   16. ستوديو برووف اول سكن بالمطبخ و التكيفات موقع مميز
   17. شقة مفروشة بالكامل دبل فيس في الخمائل الشيخ زايد
   18. ألترا سوبر لوكس أول سكن بالمطبخ والتكييفات والجراج
   19. أول سكن بمطبخ وتكييفات مركزية ودرسينج فيو لاندسكيب
   20. أول سكن بمطبخ-تكييفات مركزية-درسينج ب ماونتن فيو
   21. فيلا فاخرة للإيجار في بالم هيلز قطامية مفروشه
   22. تاون هاوس مفروش بالكامل في ميفيدا
   23. شقة 156م بجاردن | أول استخدام - فرش فندقي
   24. فيلا مفروشه باحسن سعر في الماركت
   25. شقة بحديقة للإيجار في سوديك إيستاون مفروشة بالكامل

========================================
  RENT PAGE 3  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=3
========================================
Found 25 cards
    1. شقة في فيليت مميزة مجهزة بالكامل للإيجار
    2. استوديو برووف للإيجار في سوديك فيليت
    3. شقة نص مفروشة للإيجار في ميفيدا
    4. شقة فاخرة للإيجار في ليك فيو ريزيدنس
    5. دوبلكس نص مفروش بكمبوند كايرو فستيفال سيتي
    6. من افضل العروض المتاحه الان في كمبوند سوديك فيليت
    7. من افضل الوحدات الفندقيه ارضي بجاردن متاحه الان
    8. شقه الترا سوبر لوكس للايجار في ليك فيو ريزيدنس
    9. للإيجار – شقة بكمبوند زايد هايتس – الشيخ زايد
   10. فيلا فاخره مع شاطئ خاص و مسبح خاص للايجار في مراسي
   11. جاردينيا هايتس 200م متشطبة بالكامل
   12. شقه مطبخ وتكييفات للايجار في ماونتن فيو هايد بارك
   13. شقة بحديقه خاصه للايجار في كمبوند فيلدج جيت
   14. فيلا للايجار امام الجامعة الامريكية بالمطبخ والتكي
   15. ستوديو 1 غ للايجار في كمبوند تاج سيتي بجوار المطار
   16. فيلا فاخرة للإيجار في كمبوند ليك فيو مساحة واسعة
   17. شقة 3نوم+ناني نص فرش بالاجهزه ايجار كايرو فيستيفال
   18. شقة غرفتين في B7 بافضل سعر للايجار بموقع مميز
   19. ستوديو مفروش برووف للايجار في كمبوند فيليت التجمع
   20. توين فيلا مفروشة للإيجار في هايد بارك التجمع الخام
   21. Luxurious Villa For Rent in Kattameya Heights
   22. شقة للايجار - فيلدج ويست - الشيخ زايد - مفروشه
   23. شقة للإيجار بالأندلس 2 التجمع الخامس 220 متر
   24. دوبلكس مفروش للإيجار بالنرجس فيلات التجمع الخامس
   25. شقه فاخره للايجار في افضل مكان بكمبوند جايد

========================================
  RENT PAGE 4  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=4
========================================
Found 25 cards
    1. شقة بحديقة أول سكن للإيجار في إيستاون | 191 متر
    2. شقة للإيجار في ميفيدا بوليفارد | مساحة كبيرة |
    3. شقة للايجر في ماونتن فيو اي سيتي التجمع الخامس
    4. شقة مودرن غرفتى نوم مفروشة تطل على المسبح
    5. شقة لقطة 185م للايجار بكمبوند جاردن هايتس اول سكن
    6. شقة للايجار بجاردن خاصه في ايستاون
    7. ستاندلون مميز ومفروش في بلاجيو
    8. فيلا ستاند الون مفروشه ومميزه في بيلاجيو
    9. شقة اول استخدام غرفتين مفروشة للايجار/ مدينتي بي6
   10. شاليه ستاند ألون مباشر على اللاجون في فوكا باي
   11. شقة بجاردن للايجار في مراسم, فيفث سكوير
   12. اقل سعر شاليه للايجار مفروش مراسي الساحل الشمالي
   13. استلام فوري توين هاوس متشطب للايجار باتيو الزهراء
   14. شقة لقطة اول سكن بكمبوند جاردن هايتس
   15. شقة فاخرة أول سكن للإيجار في ليك فيو
   16. شقه ارضي بحديقه مودرن في كمبوند في الجولدن سكوير
   17. شقه لقطه ايجار جديد في التجمع الخامس في الحي التال
   18. شقه للايجار قانون جديد الياسمين 8 فيلات التجمع الا
   19. فرش وتشطيبات فندقيه وحديثه / موقع مميز
   20. شقة فندقية للايجار بسعر مميز - أول سكن في ميفيدا
   21. شقة 3 غرف نوم مع مسبح خاص حديقة في القاهرة الجديدة
   22. شقة مفروشة مودرن للإيجار بالمعادي نيركو
   23. شقة عصرية للإيجار في المعادي سرايات
   24. شقة مفروشة بوليفارد 2 غرفة ماستر | ميفيدا إعمار
   25. مطبخ وتكيفات / سعر مميز / كمبوند امن وحمامات سباحه

========================================
  RENT PAGE 5  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=5
========================================
Found 25 cards
    1. للإيجار | دوبلكس أرضي مميز في O West
    2. فرصه في ارقي كمبوند بتشطيب كامل وبالمطبخ وتكيفات
    3. شقة فندقيه مفروشة غرفتي نوم للإيجار مفيدا بوليفارد
    4. شقه نص مفروشه اول سكن قريبه من جميع الكلوب هاوس
    5. شقة مفروشة مودرن و بتشطيبات سوبر لوكس في التجمع
    6. للإيجار بحري اول سكن بالمطبخ لافيستا
    7. شقه موقع مميز بالم باركس سوبر لوكس للايجار .
    8. شقة علي مساحات خضراء سوبر لوكس بالم باركس ايجار .
    9. شقة مودرن للإيجار بالقرب من CAC دجلة المعادي
   10. فيلا مميزة - للايجار مفروش - كمبوند الربوة - زايد
   11. دوبلكس متشطب بالتكييفات و المطبخ علي حمام السباحة
   12. شقه علي بحيرة سوبر لوكس في نيو جيزة ايجار .
   13. شقه مودرن للإيجار في سرايات المعادي موقع مميز
   14. اول سكن شقه للايجار ٣ غرف مفروشه بالكامل براند
   15. شقة مفروشة بالكامل للإيجار | أبراج زد – البرج C
   16. شقة سوبر لوكس للايجار بالمطبخ في اللوتس الشمالية
   17. شقة للايجار مفروشة باللوتس الجنوبية بالتجمع ال5
   18. شقة فندقية للإيجار في الرحاب فرش فندقي بالكامل
   19. استوديو مودرن بتراث للإيجار في دجله المعادي
   20. بنتهاوس للايجار بالاجهزة في ماونتن فيو اكزيكتيف
   21. شقة مفروشة للايجار سوديك ايستاون ,
   22. فيلا للايجار الربوة 900م حمام سباحة مطبخ وتكييفات
   23. توين هاوس للايجار هايد بارك,
   24. فيلا مفروشة للايجار هايد بارك,
   25. شقة 3 غرف نوم مع حديقة خاصة في القاهرة الجديدة

========================================
  RENT PAGE 6  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=6
========================================
Found 25 cards
    1. شقة للإيجار بالمطبخ وتكييفات في بالم باركس
    2. El Gouna Sabina Twin Villa with Lagoon Access
    3. شقه فندقيه مفروشه بالكامل للايجار
    4. فيلا الترا مودرن بحمام سباحه برايم لوكيشن
    5. شقة متشطبة بالمطبخ و التكيفات - فيو مميز - اقل سعر
    6. شقه مميزه نص مفروش في كمبوند فييليت
    7. استوديو مفروش بالكامل للايجار بالتجمع الخامس .
    8. استوديو مفروش بالكامل للايجار داخل كمبوند .
    9. استوديو مفروش للايجار بالقرب من كايرو فيسيتيفال.
   10. فيلا 5 غرف فاخرة صف اول علي البحر للايجار في مراسي
   11. استوديو مفروش بالكامل للايجار داخل كمبوند .
   12. توين هاوس بحمام سباحه خاص للايجار في قطامية ديونز
   13. استوديو مفروش للايجار امام الجامعه الامريكيه .
   14. استوديو مفروش بالكامل للايجار بالتجمع الخامس .
   15. استوديو مفروش للايجار داخل كمبوندامام AUC .
   16. استوديو مفروش للايجار بالقرب من كايرو فيستيفال .
   17. فيلا بحمام سباحة للإيجار بالمعادي السرايات
   18. شقه للايجار تشطيب مودرن في كورت يارد بيفرلي هيلز
   19. شقة 180 متر مربع مع 3 غرف نوم في القاهرة الجديدة
   20. شقه 160م بجاردن متشطب للايجار سوديك التجمع الخامس
   21. شاليه إطلاله مباشرة علي المارينا للايجارفي مراسي
   22. شقة مفروشة للإيجار في ميفيدا أفينيو ريزيدنس
   23. شقه 160م للايجار سوديك التجمع الخامس تشطيب مميز
   24. للإيجار: شقة بمساحة 140 متر بالتكييفات والمطبخ
   25. شقة للإيجار - موقع مميز - فيفث سكوير

========================================
  RENT PAGE 7  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=7
========================================
Found 25 cards
    1. شقه بالمطبخ و التكييفات اول سكن فى فيفث سكوير
    2. شقة للإيجار في فيفث سكوير | 172 متر
    3. شقة للإيجار في فيفث سكوير | 250 متر | تشطيب كامل
    4. شقة للإيجار في فيفث سكوير المراسم | 160 متر
    5. شقة مفروشة في 90 أفينيو | فيو رائع بسعر مغرى
    6. شقة واسعة ومضيئة في موقع مميز بأكتوبر
    7. موجودة في مرحلة Tulwa الهادية والمميزة
    8. دوبلكس أرضي للإيجار في بالم باركس بتشطيب جديد
    9. شقة مفروشة للايجار في البنفسج عمارات امام واتر واي
   10. شقه للايجار بالمطبخ والتكييفات كمبوند فيفث سكوير
   11. شقة نصف مفروش للأيجار في أيستاون
   12. فيلا للايجار في ميفيدا
   13. فرصه لن تتكرر متشطبه بالكامل ومفروشه بجميع الاجهزه
   14. فيلا فاخرة للايجار في ميفيدا اعمار
   15. Luxurious Twinhouse for Rent in Mivida
   16. استوديو مفروش بالكامل للإيجار في المعادي الجديدة
   17. شقة 234م للإيجار في ليك فيو ريزيدنس
   18. سوبر لوكس شقة بالتكيفات والمطبخ كمبوند غرب الجولف
   19. بنتهاوس للإيجار–كمبوند ريجينتس بارك–القاهرة الجديد
   20. الايجار اليومى جونير شاليه بحديقة مفروش بالكامل
   21. شقة مميزه اول استخدام للايجار في V Residence
   22. فيلا مفروشة بالكامل في الياسمين 5
   23. شقه 135م نص مفروش للايجار بالمراسم
   24. شقة للإيجار المفروش سبورتنج (ش أبو قير)
   25. ارضي بحديقة ألترا مودرن مفروش بالكامل

========================================
  RENT PAGE 8  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=8
========================================
Found 25 cards
    1. امتلك فرصه استثمار الترا سوبر لوكس جاهزه للاستلام
    2. شقة للإيجار – جنوب الأكاديمية أ – التجمع الخامس
    3. شقة مفروشه بالكامل اول سكن للايجار فى هايد بارك
    4. شقة للايجار فى كفر عبده - مطلات مفتوحة
    5. بسعر مميز-على لاندسكيب(بالمطبخ/التكييفات/سخانات)
    6. شقة ارضي بجاردن-لوكيشن مميز-للأيجار في أيستاون
    7. دور أرضي جديد للإيجار في سرايات المعادي
    8. مفروش فرش مودرن اول سكن تشطيب فندقي موقع مم
    9. مفروش راقي جد اول سكن تشطيب فندقي قريبه من الخدمات
   10. شقة للإيجار في مدينتي – القاهرة الجديدة شقة فاخرة
   11. شقة فندقية للايجار في بريفادو مدينتي اول سكن
   12. مفروش فرش مودرن اول سكن تشطيب فندقي موقع مم
   13. شقة 3 غرف مفروشة للايجار ف كمبوند المراسم التجمع
   14. أقل سعر في السوق شقة مفروشة للإيجار في ليك فيو
   15. شقة للإيجار -بالم هيلز تشطيب فاخر | مطبخ وتكييفات
   16. اول سكن - مطبخ و تكييفات - الترا سوبر لوكس
   17. اقل سعر شقة أرضي بجاردن مفروشة للإيجار في فيليت
   18. شقة للأيجار كمبوند ديستريكت 5 ,
   19. استوديو بجاردن مفروش بالكامل ف المراسم
   20. فيلا مستقلة - سوبر لوكس - وودفيل ايجار
   21. شقه 215م نص مفروش للايجار في ليك فيو
   22. شقة للإيجار في ليك فيو ريزيدنس نص مفروش
   23. شقه للايجار في اب تاون كايرو الفورتين
   24. فيلا مفروشه للإيجار الياسمين 5 فيلات بالتجمع الاول
   25. شقة مفروشة للإيجار بالياسمين 5 فيلات قرب التسعين

========================================
  RENT PAGE 9  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=9
========================================
Found 25 cards
    1. شقه مفروشه للايجار بدار مصر القرنفل امام بوابه 6
    2. شقة مفروشة في هايد بارك قرب مول CFC بالتجمع ال5
    3. شقه مفروشه فرش مودرن بالكامل للايجار في فيليت
    4. جاهزة للسكن – تشطيب راقي – سعر قابل للتفاوض
    5. فيلا مستقلة أول استخدام في ميفيدا - مفروشة بالكامل
    6. شقة للإيجار في ليك فيو - مفروشة بالكامل فرش مودرن
    7. شقة للإيجار في إيستاون -مفروشة بالكامل - موقع مميز
    8. تاون هاوس فاخرمفروش بالكامل للإيجار في فيليت
    9. شقه مفروشه للايجار سبورتنج مكيفه
   10. فيلا للايجار مفروش في ستون بارك
   11. شقة مفروشة مودرن للإيجار في دجلة المعادي
   12. شقة فندقيه 3غرفة نوم ماستر للايجار اول سكن بالدقي
   13. شقة للايجار مفروشة وجاهزة بجوار افنيو مول -الرحاب
   14. شقة 3 غرف نوم مفروشة بالكامل مع إطلالة مميزة
   15. شقة مفروشة الترا مودرن للايجار في ايستاون - سوديك
   16. للايجار في بالم باركس شقه 90م نص فرش موقع مميز
   17. توين هاوس للايجار في باتيو الزهراء اول سكن
   18. للإيجار شقة بجاردن فندقية مفروشة 4غرف بستون 50 ألف
   19. دوبلكس بحديقة خاصة للإيجار في إيستاون | 248 متر
   20. شقة مفروشة بحديقة للإيجار في ليك فيو ريزيدنس
   21. دوبلكس متشطب بالكامل بسعر مش هيتكرر - اميز موقع
   22. تشطيبات خاصه / فرش فندقي / اول استخدام
   23. شقه فندقيه 3 غرف متاحه الان في كمبوند فيليت سوديك
   24. شقة موقع مميز سوبر لوكس كازا ، الشيخ زايد ايجار
   25. شقة مفروش للإيجار بالرحاب فرش راقي جدا اول سكن

========================================
  RENT PAGE 10  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=10
========================================
Found 25 cards
    1. شقه مودرن غرفتين للايجار في كمبوند ليك فيو ريزيدنس
    2. اشيك تاون هاوس للإيجار بالمطبخ والتيكفات في ليان
    3. شقة عصرية للإيجار في سرايات المعادي القاهرة مصر
    4. شقة مفروشة بالكامل للإيجار في إيستاون
    5. للايجار شقه 3 غرف سكن اول بالمطبخ و بالتكيفات
    6. شقه مميزه بالمطبخ والتكيفات والاجهزه 205م-ايستاون
    7. دوبلكس مميز بجاردن بالمطبخ والاجهزه والتكيفات
    8. ألترا سوبر لوكس بمطبخ وتكييفات وجراج فيو لاندسكيب
    9. امتلك الان فرصه شقه متشطبه بالكامل وبافضل لوكيشن
   10. شقة مفروشة حديثة في فيليت - سكاي كوندوز
   11. بنتهاوس بتراس خاص في المعادي سرايات
   12. فرصة مميزه للايجار بسيليا العاصمة الادارية شقة3نوم
   13. شقه الايجار في صواري ارضي ب جاردن ٢٨ الف شهرياً
   14. شقة مفروشه الترا مودرن بسعر مميز اقل من السوق
   15. تاون ريسيل 357م تشطيب مودرن بالمطبخ والتكييفات
   16. شقه مفروشة للايجار في رشدي شارع ابوقير
   17. شقه مفروشة للايجار في كفر عبده فرش فاخر
   18. شقة ارضي بجاردن للايجار في ويستاون
   19. شقه فندقيه مميزه ايجار الرحاب 2 ,امام السوق الشرقى
   20. شقة مفروشة للايجار في مدينة الرحاب بجوار الخدمات
   21. فيلا اول استخدام للايجار في أب تاون كايرو
   22. فيلا جاهزة للسكن ايجار مفروشة باقل سعر فى التجمع
   23. شقة مفروشة بكمبوند بالم هيلز نيو كايرو
   24. شقة للايجار - كمبوند ذا ادرس - الشيخ زايد - مفروش
   25. شقة للايجار - الخمائل - الشيخ زايد - فرش فندقي

========================================
  RENT PAGE 11  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=11
========================================
Found 25 cards
    1. شقتك لازم تكون أول سكن فرصة ليك سعر واناقة في شقتك
    2. شقة مميزه بفرش فاخر للإيجار في سوديك فيليت
    3. دوبلكس مميز اول استخدام بالمطبخ والاجهزه والتكيفات
    4. شقه ارضي بجاردن- فيو لاند سكيب اول استخدام-فيليت
    5. شقة فاخرة للإيجار في بادية بالم هيلز
    6. شقة للإيجار في ليك فيو ريزيدنس بالتكييفات المطبخ
    7. شقه موقع مميز بالم باركس سوبر لوكس للايجار .
    8. شقة فاخرة أول سكن بحديقة خاصة للإيجار في إيستاون
    9. شقة شبه مفروشة للإيجار في معادي سرايات
   10. اي فيلا اول استخدام للايجار بتشطيب عالي والمطبخ
   11. شقة اول استخدام للايجار متشطبة بالمطبخ والتكييفات
   12. استديو للايجار بفرش مودرن وبالمطبخ والتكييفات
   13. اول استخدام|شقة مفروشة بالكامل 150م وكاملة الاجهزة
   14. للايجار| شقة بجاردن خاصة مفروشة ومجهزة بالكامل
   15. شقة فاخرة مع جاردن للايجار مفروشة ومجهزة بالكامل
   16. بنتهاوس 233م مرحلة ثانية للايجار في فيفث سكوير
   17. قطامية ديونز-تاونهاوس375م بتكيفات صف ثاني عالجولف
   18. توين هاوس للايجار اويست -موقع متميز
   19. لليجار ستوديو 75 متر ساكن اول بالمطبخ والتكييفات
   20. للايجار شقه اول سكن 3 غرف بالمطبخ وبالتكييفات
   21. بنتهاوس مع تراس للإيجار في دجلة المعادي
   22. تريبلكس بالرووف - مطبخ و اجهزة و تكييفات
   23. شقه الايجار في صواري ب 22الف في الشهر
   24. شقه 116م للايجار اويست -موقع متميز
   25. شقة ارضي للايجار او ويست اوراسكم

========================================
  RENT PAGE 12  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=12
========================================
Found 25 cards
    1. شقه للايجار في اويست مساحه 200 متر
    2. شقة للإيجار في ليك فيو ريزيدنس – القاهرة الجديدة
    3. شقة باطلالة مميزة علي حمام السباحه للايجارفي فيليت
    4. شقة 2نوم مفروشة بالكامل للإيجارفي كمبوند هايد بارك
    5. شاليه اطلالة صف اول علي المسبح للإيجار مراسي فرونت
    6. شقة للايجار في مراسم- فيفث سكوير
    7. شقة للايجار في مراسم, فيفث سكوير
    8. بنتهاوس مطبخ وتكييفات للايجار في المراسم
    9. شقه مطبخ وتكييفات للايجار في فيفث سكوير -المراسم
   10. اي فيلا جاردن للايجار في ماونتن فيو هايد بارك
   11. شقه مودرن للإيجار مع موقع خيالي بدجله المعادي
   12. شقة بالمطبخ والتكييفات للإيجار في إيستاون
   13. شقة فاخرة للإيجار تطل على الليك في ليك فيو ريزيدنس
   14. بسعر لقطه جدا شقه مفروشه للايجار في روضه زايد
   15. شقة للايجار مفروشه سوبر لوكس فى ايستاون
   16. استدويو مفروشه بسعر لقطه في كازا بيفيرلي هيلز .
   17. شقة مفروشة للايجار بالياسمين 6 فيلات التجمع الاول
   18. شقه205م للايجار اول سكن بالتكيفات بالتجمع الخامس
   19. شقة مودرن مفروشة للايجار بالياسمين 7 قرب التسعين
   20. دوبلكس 370م مفروش للايجار التجمع ال5 قرب التسعين
   21. شقة مفروشة للايجار بدار مصر القرنفل امام بوابه 6
   22. شقه مفروشه للايجار النرجس عمارات قرب المستشفي جوي
   23. شقة للايجار سكني و إداري بالتكييفات بالتجمع الخامس
   24. شقه للايجار في جنوب الاكاديميه أ قرب مجمع البنوك
   25. شقة مفروشة للإيجار في ليك فيو ريزيدنس

========================================
  RENT PAGE 13  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=13
========================================
Found 25 cards
    1. شقة للايجار في القرنفل فيلات في التجمع الاول
    2. شقه للايجار في كمبوند قطامية جاردنز بالتجمع الخامس
    3. شقه مودرن مفروشه للايجار في جنوب الاكاديميه أ
    4. شقه للايجار في الشيخ زايد
    5. شقه للايجار بالمطبخ و التكييفات -اول سكن
    6. شقه مفروشه فندقيه 3 غرف في افنيوز ميفيدا
    7. شاليه مميز للايجار في سيشيل سيدي عبدالرحمن
    8. بنتهاوس بروف كبير للأيجار مفروش بالتكيفات والمطبخ
    9. شقه فاخره للايجار فرش مودرن و نظيف في وبيستاون .
   10. اقل سعر وحدة فندقية 5 غرف بالتجمع الخامس
   11. استوديو مفروش بالكامل أمام الجامعة الأمريكية
   12. فيلا مستقلة للإيجار بتشطيب كامل في ميفيدا
   13. شقة 165م للإيجار في ماونتن فيو آي سيتي
   14. شقة فاخرة ألترا سوبر لوكس للإيجار -أول سكن بالمطبخ
   15. شقة أول سكن بالتكييفات والمطبخ -ماونتن فيو آي سيتي
   16. فيلا فاخر للإيجار في كمبوند ليان –باقل سعر
   17. شقة للايجار في جاسبر نيو جيزه - فيو لاندسكيب مميز
   18. مفروش راقي جد اول سكن تشطيب فندقي قريبه من الخدمات
   19. في ارقى مراحل مدينتي وبسعر لقطه لن يتكرر
   20. دوبلكس مفروش للايجار بمكان راقي المعادي سرايات
   21. ارخص شقه بالمطبخ و التكييفات في كمبوند قريبه المول
   22. فيلا مستقلة للايجار نصف مفروشة في أب تاون كايرو
   23. شقة 3 غرف نوم مفروشة بالكامل لايك فيو ريزتنس
   24. فرش فندقي / تشطيبات حديثه / سعر مميز
   25. شقة للايجار بالأجهزة في ميفيدا

========================================
  RENT PAGE 14  →  https://www.propertyfinder.eg/ar/search?c=2&fu=0&rp=m&ob=mr&page=14
========================================
Found 25 cards
    1. توين هاوس الترا مودرن للايجار في سوديك فيليت
    2. شقة مفروشة بفرش مودرن للايجار في ليك فيو ريزيدنس
    3. شقة مفروشه الترا مودرن سوبر لوكس بسعر مميز
    4. شقة فاخرة أول سكن بفرش مودرن للايجار في ايستاون
    5. شقة مفروشة للإيجار في إيستاون | 156 متر
    6. شقة أول سكن للايجار مفروشة بفرش مودرن في ميفيدا
    7. قصر فاخر للغاية للإيجار في مارينا 5
    8. شقة مفروشة بالكامل للإيجار في هايد بارك | 145 متر
    9. شقة مفروشة للأيجار فيليت ريدنس ,
   10. Luxury Stand Alone For Rent in Uptown Cairo

,title,price,location,property_type,bedrooms,bathrooms,area,listing_type,agency_logo,agency_name,publish_date,publish_time,listing_url,image_urls,source
0,فرصة مميزة للإيجار | توين هاوس فاخر في PK1,٢٥٠٬٠٠٠ جنيه/ شهرياً,"بالم هيلز قطامية, كمبوندات القطامية, القطامية,...",منزل مزدوج,4,5,٤٠٠ متر مربع,Rent,https://static.shared.propertyfinder.eg/media/...,None,10.06.2026,11:12 PM,https://www.propertyfinder.eg/ar/plp/rent/twin...,https://static.shared.propertyfinder.eg/media/...,Property Finder Egypt
1,شقة فاخرة للإيجار في كمبوند ووتر واي | موقع متميز,١٠٬٠٠٠ جنيه/ شهرياً,"ووترواي إيست, التجمع الخامس, مدينة القاهرة الج...",شقة,3,4,٢٤٧ متر مربع,Rent,https://static.shared.propertyfinder.eg/media/...,None,11.06.2026,12:12 AM,https://www.propertyfinder.eg/ar/plp/rent/apar...,https://static.shared.propertyfinder.eg/media/...,Property Finder Egypt
2,دور أرضي مفروش مودرن للإيجار في ستون ريزيدانس,٧٢٬٠٠٠ جنيه/ شهرياً,"ستون ريزيدنس, كمبوندات التجمع الخامس, التجمع ا...",شقة,4,3,٢٠٠ متر مربع,Rent,https://static.shared.propertyfinder.eg/media/...,None,11.06.2026,12:12 AM,https://www.propertyfinder.eg/ar/plp/rent/apar...,https://static.shared.propertyfinder.eg/media/...,Property Finder Egypt
3,هاسيندا وايت دوبلكس أرضى للإيجار 4 غرف وناني,١٬١٠٠٬٠٠٠ جنيه/ شهرياً,"هاسييندا وايت, سيدي عبد الرحمن, الساحل الشمالي",دوبلكس,4,5,٢٠٠ متر مربع,Rent,https://static.shared.propertyfinder.eg/media/...,None,10.06.2026,10:12 PM,https://www.propertyfinder.eg/ar/plp/rent/dupl...,https://static.shared.propertyfinder.eg/media/...,Property Finder Egypt
4,شقة للإيجار جنوب الأكاديمية أ – موقع ذهبي,٥٠٬٠٠٠ جنيه/ شهرياً,"محور العروبة, المنطقة أ, حى جنوب الاكايمية, مد...",شقة,3,2,٢١٠ متر مربع,Rent,https://static.shared.propertyfinder.eg/media/...,None,10.06.2026,10:12 PM,https://www.propertyfinder.eg/ar/plp/rent/apar...,https://static.shared.propertyfinder.eg/media/...,Property Finder Egypt

## Cell 6 — Merge all results & save to CSV

Combines whichever DataFrames exist (`sale_df`, `rent_df`) into a
single file called **`propertyfinder_properties.csv`**.

> If you only ran one of the two scrapers, the missing DataFrame is simply skipped.

In [15]:
# ── Collect whichever DataFrames were created ────────────────────
COLUMNS = [
    "title", "price", "location", "property_type", "bedrooms", "bathrooms",
    "area", "listing_type", "agency_logo", "agency_name",
    "publish_date", "publish_time", "listing_url", "image_urls", "source",
]

available = {}
for name, var in [("Sale", "sale_df"), ("Rent", "rent_df")]:
    try:
        df_check = eval(var)
        if not df_check.empty:
            available[name] = df_check
            print(f"  ✅ {name:<6} — {len(df_check):>4} listings")
        else:
            print(f"  ⚠️  {name:<6} — DataFrame is empty, skipping")
    except NameError:
        print(f"  ℹ️  {name:<6} — not scraped yet, skipping")

if not available:
    print("\n❌ No data to merge. Run at least one scraper first.")
else:
    OUTPUT_FILE = "propertyfinder_properties.csv"

    combined = pd.concat(available.values(), ignore_index=True)
    existing_cols = [c for c in COLUMNS if c in combined.columns]
    combined = combined[existing_cols]

    combined.to_csv(OUTPUT_FILE, index=False, encoding="utf-8-sig")

    print(f"\n{'─'*40}")
    print(f"  Total listings : {len(combined)}")
    print(f"  Saved to       : {OUTPUT_FILE}")
    print(f"{'─'*40}")

    combined.head(10)

  ✅ Sale   — 1250 listings
  ✅ Rent   — 1250 listings

────────────────────────────────────────
  Total listings : 2500
  Saved to       : propertyfinder_properties.csv
────────────────────────────────────────

In [16]:
import re

def normalize_logo_url(url):
    """شيل الـ query string (?v=...) والـ resolution (/178x98) من الـ URL."""
    if not url or str(url).startswith("data:"):
        return None
    url = str(url).split("?")[0]
    return re.sub(r'/\d+x\d+(\.\w+)$', r'\1', url)

# ── Normalise الاتنين ─────────────────────────────────────────────
combined["agency_logo_norm"]    = combined["agency_logo"].apply(normalize_logo_url)
agencies_df["agency_logo_norm"] = agencies_df["agency_logo"].apply(normalize_logo_url)

# ── Build lookup ──────────────────────────────────────────────────
logo_to_name = (
    agencies_df.dropna(subset=["agency_logo_norm"])
    .set_index("agency_logo_norm")["agency_name"]
    .to_dict()
)

# ── Update agency_name ────────────────────────────────────────────
combined["agency_name"] = combined["agency_logo_norm"].map(logo_to_name)
combined.drop(columns=["agency_logo_norm"], inplace=True)

# ── Save ──────────────────────────────────────────────────────────
combined.to_csv("propertyfinder_properties.csv", index=False, encoding="utf-8-sig")

# ── Summary ───────────────────────────────────────────────────────
matched   = combined["agency_name"].notna().sum()
no_logo   = combined["agency_logo"].isna().sum()
print(f"✅ Matched         : {matched}")
print(f"⚠️  No logo (NaN)  : {no_logo}")
combined[["agency_logo", "agency_name"]].dropna(subset=["agency_logo"]).head(10)

✅ Matched         : 2322
⚠️  No logo (NaN)  : 178

                                         agency_logo          agency_name
0  https://static.shared.propertyfinder.eg/media/...    Spade consultancy
1  https://static.shared.propertyfinder.eg/media/...   Property Hills One
2  https://static.shared.propertyfinder.eg/media/...    Spade consultancy
3  https://static.shared.propertyfinder.eg/media/...    Spade consultancy
4  https://static.shared.propertyfinder.eg/media/...    Spade consultancy
5  https://static.shared.propertyfinder.eg/media/...  Platinum Properties
6  https://static.shared.propertyfinder.eg/media/...  Platinum Properties
7  https://static.shared.propertyfinder.eg/media/...  Platinum Properties
8  https://static.shared.propertyfinder.eg/media/...  Platinum Properties
9  https://static.shared.propertyfinder.eg/media/...                NABAJ